"""
Incident families, part 1 of 2.

Each family describes one recognizable failure mode: how it starts, how it
looks in logs and alerts as it unfolds, how it is mitigated, and the
runbook, postmortem, GitHub issue, and search-question text that goes with
it. The generator instantiates each family several times across the 90-day
window with randomized timing, region, pods, and numbers.

Phase templates are (service, severity, event_type, text). event_type is
one of: log, alert, k8s_event. Placeholders are filled by the generator:
  {pct} {n} {n2} {ms} {slow_ms} {pod} {node} {region} {trace} {id}
  {deploy_id} {version} {prev_version} {oncall} {incident_id} {date}
"""

PHASES = ["precursor", "onset", "peak", "mitigation", "recovery"]

FAMILIES_A = [
# ---------------------------------------------------------------------------
{
    "key": "db_pool_exhaustion",
    "title": "Database connection pool exhaustion after payments deploy",
    "primary": "checkout-api",
    "services": ["checkout-api", "payments", "postgres"],
    "error_code": "PG_53300",
    "trigger": "deploy",
    "trigger_service": "payments",
    "trigger_summary": "Increase payment authorization retries from 3 to 5 and hold the DB transaction open across retries",
    "duration": (40, 95),
    "phases": {
        "precursor": [
            ("payments", "info", "log", "started {pod} version={version} commit={sha} listening on :8080"),
            ("postgres", "info", "log", "connection authorized: user=app_payments database=tigerlily ssl=on"),
            ("payments", "warning", "log", "connection pool utilization {pool_pct}% (active={pool_active} max=50), was 40% before {deploy_id}"),
            ("postgres", "warning", "log", "active connections at 78% of max_connections (390/500)"),
        ],
        "onset": [
            ("payments", "warning", "log", "payment authorize held transaction open for {slow_ms}ms across 5 retry attempts trace={trace}"),
            ("postgres", "warning", "log", "active sessions reached 95% of max_connections (475/500)"),
            ("checkout-api", "warning", "log", "waiting for database connection from pool for {ms}ms (pool exhausted, waiting={n}) trace={trace}"),
            ("payments", "error", "log", "pgx: acquire timeout after 5s, pool size 50 all busy trace={trace}"),
            ("postgres", "warning", "alert", "[FIRING] PostgresConnectionsHigh instance=tigerlily-primary connections=482 max=500"),
        ],
        "peak": [
            ("checkout-api", "error", "log", "connection pool exhausted after payment deploy: 0 idle, {n} waiting, acquire timeout trace={trace}"),
            ("postgres", "error", "log", "FATAL: sorry, too many clients already (SQLSTATE 53300)"),
            ("payments", "critical", "log", "checkout requests timing out while acquiring database connection, p99={slow_ms}ms error_rate={pct}%"),
            ("checkout-api", "error", "log", "POST /v1/checkout/{id}/confirm 503 database unavailable trace={trace}"),
            ("checkout-api", "critical", "alert", "[FIRING] CheckoutErrorRateHigh error_rate={pct}% threshold=2% window=5m"),
            ("payments", "critical", "alert", "[FIRING] PaymentsLatencyP99 p99={slow_ms}ms threshold=1500ms"),
            ("api-gateway", "error", "log", "route /v1/checkout 504 upstream checkout-api timed out after 30s trace={trace}"),
            ("postgres", "critical", "alert", "[FIRING] PostgresConnectionsExhausted connections=500 max=500"),
        ],
        "mitigation": [
            ("payments", "info", "log", "incident {incident_id}: {oncall} initiated rollback of payments to {prev_version}"),
            ("payments", "info", "log", "rolling back {deploy_id}: replicas transitioning to {prev_version}"),
            ("postgres", "info", "log", "terminating {n} idle-in-transaction sessions older than 60s (manual: {oncall})"),
            ("payments", "info", "log", "started {pod} version={prev_version} commit={sha} listening on :8080"),
        ],
        "recovery": [
            ("postgres", "info", "log", "active connections at 41% of max_connections (205/500)"),
            ("checkout-api", "info", "log", "connection pool stats: active={idle} idle={idle} waiting=0 max=50"),
            ("checkout-api", "info", "alert", "[RESOLVED] CheckoutErrorRateHigh error_rate=0.3%"),
            ("payments", "info", "alert", "[RESOLVED] PaymentsLatencyP99 p99=210ms"),
            ("postgres", "info", "alert", "[RESOLVED] PostgresConnectionsExhausted connections=198"),
        ],
    },
    "runbook": {
        "Symptoms": "Checkout and payment requests time out or return 503 while acquiring a database connection. Postgres logs show 'too many clients already' (SQLSTATE 53300). Connection count on the primary sits at or near max_connections. Error rate climbs within minutes of a deploy to a service that talks to the primary.",
        "Detection": "Alerts: PostgresConnectionsHigh (warning at 90%), PostgresConnectionsExhausted (critical at 100%), CheckoutErrorRateHigh. Dashboard: Postgres Primary > Connections by application_name. A single application_name owning most connections points to the culprit service.",
        "Diagnosis": "Run SELECT application_name, state, count(*) FROM pg_stat_activity GROUP BY 1,2 ORDER BY 3 DESC. Look for many 'idle in transaction' sessions from one app. Check the deploy timeline for that service in the last 30 minutes. Compare the new version's connection handling: transactions held across external calls or retries are the usual cause.",
        "Mitigation": "Roll back the offending service to the previous version first; do not try to fix forward during the incident. If the primary is still saturated after rollback, terminate idle-in-transaction sessions older than 60s with pg_terminate_backend. As a last resort raise max_connections temporarily, but this needs a restart and shifts the problem to memory.",
        "Verification": "Connections on the primary drop below 60% within two minutes of rollback. CheckoutErrorRateHigh resolves. Checkout p99 returns under 800ms. Confirm no lingering idle-in-transaction sessions.",
        "Escalation": "Page data-infra if the primary does not recover after rollback and session termination. Page payments-platform lead if rollback itself fails. Open a SEV1 if checkout availability is below 95% for more than 10 minutes.",
    },
    "root_cause": "A payments deploy changed the authorization flow to retry the payment processor up to five times while holding the surrounding database transaction open. Under normal processor latency each request now held a connection for several seconds instead of tens of milliseconds, and the pool of 50 per replica across 12 replicas saturated the primary's max_connections of 500 within minutes.",
    "contributing": [
        "The change was reviewed for correctness of the retry logic but not for connection hold time.",
        "Staging runs with 2 replicas and a processor stub that returns instantly, so pool pressure never appeared in pre-production.",
        "No connection-pool-utilization alert existed at the service level; the first alert fired from Postgres at 90%.",
        "Checkout-api shares the same primary and had no bulkhead, so an unrelated service's connection use took it down.",
    ],
    "impact": "Checkout success rate dropped to {impact_pct}% for {impact_min} minutes. Approximately {impact_orders} checkout attempts failed or timed out. Payments already authorized were not affected.",
    "action_items": [
        "Move payment processor retries outside the database transaction boundary.",
        "Add per-service pool utilization alert at 80% (owner: payments-platform).",
        "Introduce PgBouncer in transaction pooling mode in front of the primary (owner: data-infra).",
        "Add a load test stage to the payments pipeline that exercises processor latency (owner: payments-platform).",
    ],
    "issues": [
        {"repo": "tigerlily/payments", "title": "Authorization retries hold DB transaction open, exhausting connection pool",
         "labels": ["bug", "sev1", "postmortem-action-item", "database"],
         "body": "During {incident_id} the retry loop added in {deploy_id} kept the transaction open for the whole retry sequence. With processor p50 around 800ms and up to 5 attempts, a single request held a connection for 4s+.\n\nProposed fix: authorize outside the transaction, then open a short transaction to persist the result. Also cap retries at 3 with a 2s total budget.\n\nSee postmortem {incident_id} for timeline."},
        {"repo": "tigerlily/db-ops", "title": "Deploy PgBouncer in transaction mode in front of tigerlily-primary",
         "labels": ["enhancement", "postmortem-action-item", "database", "reliability"],
         "body": "Action item from {incident_id}. Every app service opens its own pool directly against the primary, so one misbehaving service can take everyone down. A transaction-mode pooler caps server connections at a fixed number and lets us give each service a bounded share.\n\nOpen questions: prepared statement handling for the Java services, and whether we lose LISTEN/NOTIFY for notifications."},
    ],
    "questions": [
        ("why do we keep running out of database connections", "semantic"),
        ("checkout timing out acquiring database connection", "semantic"),
        ("SQLSTATE 53300", "keyword"),
        ("too many clients already", "keyword"),
        ("incident where a payments deploy saturated postgres max_connections", "hybrid"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "tls_cert_expiry",
    "title": "Expired TLS certificate on edge proxy",
    "primary": "edge-proxy",
    "services": ["edge-proxy", "api-gateway"],
    "error_code": "CERT_EXPIRED",
    "trigger": "cert",
    "duration": (25, 70),
    "phases": {
        "precursor": [
            ("edge-proxy", "warning", "log", "cert-manager: certificate api-tigerlily-tls expires in {n} days, renewal attempt failed: ACME challenge for api.tigerlily.example returned 403"),
            ("edge-proxy", "warning", "log", "cert-manager: retrying renewal of api-tigerlily-tls, attempt {n2}, next retry in 8h"),
            ("edge-proxy", "warning", "alert", "[FIRING] CertificateExpiringSoon cn=api.tigerlily.example days_left={n2}"),
        ],
        "onset": [
            ("edge-proxy", "error", "log", "TLS certificate expired for api.tigerlily.example (notAfter={date}), handshakes will fail"),
            ("edge-proxy", "error", "log", "TLS handshake error from {ip}: certificate has expired sni=api.tigerlily.example"),
            ("api-gateway", "warning", "log", "inbound request volume dropped {pct}% in 60s window, upstream health checks still passing"),
        ],
        "peak": [
            ("edge-proxy", "error", "log", "TLS handshake error from {ip}: certificate has expired sni=api.tigerlily.example"),
            ("edge-proxy", "critical", "alert", "[FIRING] CertificateExpired cn=api.tigerlily.example"),
            ("edge-proxy", "critical", "alert", "[FIRING] EdgeTLSHandshakeFailures rate={n}/s threshold=50/s"),
            ("api-gateway", "critical", "alert", "[FIRING] TrafficDropAnomaly requests_per_min={n} expected={n_plus}00 drop={pct}%"),
            ("checkout-api", "info", "log", "served {n} requests in last 60s, p50=42ms p99=180ms error_rate=0.1%"),
            ("edge-proxy", "error", "log", "synthetic probe checkout-flow failed: x509: certificate has expired or is not yet valid"),
        ],
        "mitigation": [
            ("edge-proxy", "info", "log", "incident {incident_id}: {oncall} fixed ACME challenge route (WAF rule 942100 was blocking /.well-known/acme-challenge)"),
            ("edge-proxy", "info", "log", "cert-manager: renewal of api-tigerlily-tls succeeded, new notAfter={date_plus90}"),
            ("edge-proxy", "info", "log", "config reload complete, 48 routes, 12 upstreams, TLS certificate rotated"),
        ],
        "recovery": [
            ("edge-proxy", "info", "log", "TLS 1.3 handshake complete cipher=TLS_AES_256_GCM_SHA384 sni=api.tigerlily.example"),
            ("edge-proxy", "info", "alert", "[RESOLVED] CertificateExpired cn=api.tigerlily.example"),
            ("edge-proxy", "info", "alert", "[RESOLVED] EdgeTLSHandshakeFailures rate=0/s"),
            ("api-gateway", "info", "alert", "[RESOLVED] TrafficDropAnomaly requests_per_min={n_plus}00"),
            ("edge-proxy", "info", "log", "synthetic probe checkout-flow passed in {ms}ms"),
        ],
    },
    "runbook": {
        "Symptoms": "Clients fail to connect with 'certificate has expired'. Backend services look healthy and quiet: request volume drops sharply while error rates inside the cluster stay at zero. Synthetic probes fail at the TLS layer before any HTTP request is sent.",
        "Detection": "Alerts: CertificateExpiringSoon (warning at 14 days), CertificateExpired (critical), EdgeTLSHandshakeFailures, TrafficDropAnomaly. Quick check: openssl s_client -connect api.tigerlily.example:443 -servername api.tigerlily.example | openssl x509 -noout -dates.",
        "Diagnosis": "Check cert-manager logs for the Certificate resource: kubectl describe certificate api-tigerlily-tls -n edge. Renewal usually failed for a mundane reason: the ACME HTTP-01 challenge path is blocked by a WAF rule or routing change, DNS for the domain changed, or the issuer secret was rotated. Note that a renewal that has been failing for weeks still only pages at expiry if the warning alert is unrouted.",
        "Mitigation": "Fix the underlying renewal blocker (most often: allow /.well-known/acme-challenge/ through the WAF and edge routes), then force a renewal with cmctl renew api-tigerlily-tls. If ACME cannot be fixed quickly, upload the emergency backup certificate from the secrets vault and reload the proxy. Never disable TLS verification on clients.",
        "Verification": "openssl s_client shows a notAfter date in the future. EdgeTLSHandshakeFailures drops to zero. Request volume at api-gateway returns to baseline within five minutes as clients reconnect.",
        "Escalation": "Page platform-infra immediately; this is a full outage of the public API. If the ACME issuer is down, contact the certificate vendor. Open a SEV1.",
    },
    "root_cause": "The edge TLS certificate for api.tigerlily.example expired. cert-manager had been attempting renewal for 19 days, but the ACME HTTP-01 challenge was blocked by a WAF rule added to stop path-scanning bots, which matched /.well-known/acme-challenge/ as a suspicious path. The CertificateExpiringSoon warning fired to a Slack channel nobody was watching.",
    "contributing": [
        "The WAF rule change was tested against application routes, not against the ACME challenge path.",
        "CertificateExpiringSoon was routed to a low-traffic Slack channel rather than the on-call pager.",
        "No synthetic monitor checked certificate validity independently of cert-manager's own status.",
    ],
    "impact": "The public API was unreachable for all clients with correct certificate validation for {impact_min} minutes. Web and mobile checkout were fully unavailable. Backend services were unaffected.",
    "action_items": [
        "Route CertificateExpiringSoon to the platform-infra pager at 14 and 7 days.",
        "Add an explicit WAF allow rule for /.well-known/acme-challenge/ and a test in the WAF rule CI.",
        "Add an external synthetic check that asserts certificate notAfter is more than 10 days out.",
        "Store an emergency certificate in the vault and document the manual rotation path.",
    ],
    "issues": [
        {"repo": "tigerlily/edge-proxy", "title": "WAF rule 942100 blocks ACME HTTP-01 challenge path, breaking certificate renewal",
         "labels": ["bug", "sev1", "postmortem-action-item", "security"],
         "body": "Root cause of {incident_id}. The path-scanning rule added to block /.well-known/ enumeration also blocked cert-manager's HTTP-01 challenge. Renewal failed silently for 19 days.\n\nFix: explicit allow for /.well-known/acme-challenge/ evaluated before the deny rules, plus a CI test that issues a challenge-style request through the WAF config."},
        {"repo": "tigerlily/edge-proxy", "title": "Route certificate expiry warnings to pager, not Slack",
         "labels": ["postmortem-action-item", "alerting"],
         "body": "CertificateExpiringSoon fired daily for two weeks before {incident_id} into #infra-notifications. Nobody saw it. Proposal: warning to pager at 14 days (business hours), critical at 7 days (24x7)."},
    ],
    "questions": [
        ("why did the site go down even though all services were healthy", "semantic"),
        ("certificate has expired", "keyword"),
        ("api traffic dropped to zero with no backend errors", "semantic"),
        ("cert-manager renewal failing ACME challenge", "hybrid"),
        ("how do I rotate the edge TLS certificate in an emergency", "semantic"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "embedding_worker_oom",
    "title": "Embedding worker OOMKilled after model rollout",
    "primary": "embedding-worker",
    "services": ["embedding-worker", "recommendations"],
    "error_code": "OOMKilled",
    "trigger": "deploy",
    "trigger_service": "embedding-worker",
    "trigger_summary": "Roll out product embedding model v3 (1024-dim, larger vocabulary) for similar-items",
    "duration": (60, 180),
    "phases": {
        "precursor": [
            ("embedding-worker", "info", "log", "started {pod} version={version} commit={sha} concurrency=4 model=product-embed-v3"),
            ("embedding-worker", "info", "log", "loading model product-embed-v3 from object-store, {n}MB weights, {n2}k vocabulary entries"),
            ("embedding-worker", "warning", "log", "worker {pod} memory {mb}MB approaching limit 2048MB"),
            ("embedding-worker", "info", "log", "job embed-product-batch started run_id={id} batch_size=256"),
        ],
        "onset": [
            ("embedding-worker", "warning", "log", "worker {pod} memory {mb_high}MB approaching limit 2048MB, RSS grew {n}MB during batch"),
            ("embedding-worker", "warning", "k8s_event", "Pod {pod}: container embedding-worker memory usage 97% of limit"),
            ("embedding-worker", "critical", "log", "worker {pod} exited with code 137 (SIGKILL) during embed-product-batch"),
            ("embedding-worker", "error", "k8s_event", "Pod {pod}: container embedding-worker terminated reason=OOMKilled exitCode=137"),
        ],
        "peak": [
            ("embedding-worker", "error", "k8s_event", "Pod {pod}: container embedding-worker terminated reason=OOMKilled exitCode=137"),
            ("embedding-worker", "warning", "k8s_event", "Pod {pod}: Back-off restarting failed container, restartCount={n2}"),
            ("embedding-worker", "warning", "log", "embedding worker OOMKilled after model rollout, {n2} restarts in 30m, batch offset={offset} never commits"),
            ("kafka", "warning", "log", "consumer lag on catalog.product-updated partition {partition} is {lag} messages (threshold 1000)"),
            ("recommendations", "warning", "log", "similar-items cache miss rate {pct}%, embeddings for {n} recently updated products missing"),
            ("recommendations", "error", "log", "GET /v1/recommendations/similar/{id} 200 served fallback (popularity) because embedding missing trace={trace}"),
            ("embedding-worker", "critical", "alert", "[FIRING] PodCrashLooping pod={pod} namespace=discovery restarts={n2}"),
            ("kafka", "warning", "alert", "[FIRING] KafkaConsumerLagHigh group=embedding-worker topic=catalog.product-updated lag={lag}"),
        ],
        "mitigation": [
            ("embedding-worker", "info", "log", "incident {incident_id}: {oncall} reducing batch_size 256 -> 32 and raising memory limit to 4096MB"),
            ("embedding-worker", "info", "k8s_event", "Deployment embedding-worker: scaled resources.limits.memory 2Gi -> 4Gi, rolling out"),
            ("embedding-worker", "info", "log", "started {pod} version={version} commit={sha} concurrency=2 model=product-embed-v3 batch_size=32"),
        ],
        "recovery": [
            ("embedding-worker", "info", "log", "job embed-product-batch completed: processed {n} records in {sec}s, peak RSS {mb}MB"),
            ("kafka", "info", "log", "consumed {n} messages from catalog.product-updated partition {partition} offset={offset} lag=0"),
            ("embedding-worker", "info", "alert", "[RESOLVED] PodCrashLooping pod={pod}"),
            ("kafka", "info", "alert", "[RESOLVED] KafkaConsumerLagHigh group=embedding-worker lag=12"),
            ("recommendations", "info", "log", "similar-items cache miss rate 2%, embedding coverage back to 99.8%"),
        ],
    },
    "runbook": {
        "Symptoms": "Embedding worker pods restart repeatedly with exit code 137 and reason OOMKilled. Consumer lag on catalog.product-updated grows because batches never commit. Recommendations serve popularity fallbacks and similar-items quality degrades. Nothing is 'down' from the user's point of view, which makes this easy to miss.",
        "Detection": "Alerts: PodCrashLooping in namespace discovery, KafkaConsumerLagHigh for group embedding-worker. Dashboard: Discovery > Embedding pipeline > RSS by pod, and the 'embedding coverage' panel on the recommendations board.",
        "Diagnosis": "kubectl describe pod on a restarted worker shows Last State: Terminated, Reason: OOMKilled. Check what changed: a new model (larger weights or vocabulary), a larger batch size, or a dependency upgrade that changed tensor memory behavior. Model weights plus one batch of activations must fit under the container limit with headroom; with v3 a 256-item batch alone needs about 1.4GB.",
        "Mitigation": "Reduce batch_size via the BATCH_SIZE env var (32 is safe for v3) and raise the memory limit to 4Gi. Either alone may be enough; do both during the incident. If the model itself is the problem, roll back to the previous model tag. The pipeline is idempotent, so lag drains on its own once workers stay up.",
        "Verification": "No new OOMKilled events for 15 minutes. Consumer lag trending toward zero. Embedding coverage on the recommendations dashboard returns above 99%.",
        "Escalation": "Page discovery on-call. If lag exceeds 100k messages, coordinate with data-infra on Kafka retention so offsets are not lost.",
    },
    "root_cause": "The product-embed-v3 model rollout increased weight size from 420MB to 910MB and embedding dimension from 768 to 1024. With the unchanged batch size of 256, peak working memory rose above the 2GB container limit, and the kernel killed the container mid-batch. Because the batch never committed its Kafka offset, each restart replayed the same batch and died at the same point.",
    "contributing": [
        "Memory limits were set for the v2 model and not revisited during the v3 rollout.",
        "The model card documented weight size but not peak inference memory at the production batch size.",
        "Staging processes a tiny catalog and never reached a full 256-item batch.",
        "PodCrashLooping in the discovery namespace was a warning, not a page.",
    ],
    "impact": "Similar-items recommendations degraded to popularity fallback for {impact_pct}% of product pages over {impact_min} minutes. No errors visible to shoppers. Estimated recommendation click-through dropped by roughly a third during the window.",
    "action_items": [
        "Add peak memory at production batch size to the model rollout checklist.",
        "Make batch size adaptive to available memory in the worker.",
        "Promote PodCrashLooping in discovery to a page during business hours.",
        "Add a staging soak that processes at least 10 full batches before promotion.",
    ],
    "issues": [
        {"repo": "tigerlily/recommendations", "title": "embedding-worker OOMKilled with product-embed-v3 at batch_size=256",
         "labels": ["bug", "sev2", "postmortem-action-item", "ml-infra"],
         "body": "From {incident_id}. v3 roughly doubled resident memory per batch. Workers died with exit 137 and replayed the same offsets on restart.\n\nShort term (done during incident): batch_size=32, limit 4Gi.\nLonger term: size batches from available memory at startup, and add a memory regression check to the model promotion pipeline."},
        {"repo": "tigerlily/recommendations", "title": "Commit Kafka offsets per sub-batch so a crash does not replay the whole batch",
         "labels": ["enhancement", "postmortem-action-item", "kafka"],
         "body": "During {incident_id} every restart replayed 256 messages and died at the same spot, so lag never moved. Committing after each 32-item sub-batch would bound the replay and let a struggling worker make progress."},
    ],
    "questions": [
        ("embedding worker keeps getting OOMKilled after model rollout", "semantic"),
        ("exit code 137", "keyword"),
        ("why are recommendations showing popular items instead of similar items", "semantic"),
        ("consumer lag growing on catalog.product-updated", "hybrid"),
        ("pod crash looping in discovery namespace", "hybrid"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "bad_deploy_npe",
    "title": "Catalog API regression returning 500s after deploy",
    "primary": "catalog-api",
    "services": ["catalog-api", "api-gateway", "cart-service"],
    "error_code": "HTTP_500",
    "trigger": "deploy",
    "trigger_service": "catalog-api",
    "trigger_summary": "Refactor variant pricing lookup to use the new price_history table",
    "duration": (15, 45),
    "phases": {
        "precursor": [
            ("catalog-api", "info", "log", "started {pod} version={version} commit={sha} listening on :8080"),
            ("catalog-api", "info", "log", "canary {deploy_id}: 10% traffic on {version}, error_rate=0.{pct}%"),
        ],
        "onset": [
            ("catalog-api", "error", "log", "GET /v2/products/{id}/variants 500 NullPointerException at PricingResolver.resolve(PricingResolver.java:142) trace={trace}"),
            ("catalog-api", "error", "log", "GET /v2/products/{id} 500 NullPointerException: price_history entry missing for variant {id} trace={trace}"),
            ("catalog-api", "warning", "log", "canary {deploy_id}: error_rate={pct}% on {version} vs 0.2% on {prev_version}, promotion continuing (threshold 5%)"),
        ],
        "peak": [
            ("catalog-api", "error", "log", "GET /v2/products/{id}/variants 500 NullPointerException at PricingResolver.resolve(PricingResolver.java:142) trace={trace}"),
            ("catalog-api", "error", "log", "GET /v2/products/{id} 500 NullPointerException: price_history entry missing for variant {id} trace={trace}"),
            ("catalog-api", "critical", "alert", "[FIRING] CatalogErrorRateHigh error_rate={pct}% threshold=2% window=5m"),
            ("api-gateway", "error", "log", "upstream catalog-api returned 500 for /v2/products/{id}, retried on next replica (also 500) trace={trace}"),
            ("cart-service", "error", "log", "GET /v1/cart/{id} 500 unhandled error: catalog-api returned 500 resolving product {id} trace={trace}"),
            ("cart-service", "warning", "log", "upstream catalog-api responded 500, serving stale cache entry age={n}s"),
            ("api-gateway", "critical", "alert", "[FIRING] GatewayUpstream5xx upstream=catalog-api rate={pct}%"),
        ],
        "mitigation": [
            ("catalog-api", "info", "log", "incident {incident_id}: {oncall} triggered rollback of {deploy_id} to {prev_version}"),
            ("catalog-api", "info", "log", "rolling back {deploy_id}: replicas transitioning to {prev_version}"),
            ("catalog-api", "info", "log", "started {pod} version={prev_version} commit={sha} listening on :8080"),
        ],
        "recovery": [
            ("catalog-api", "info", "log", "GET /v2/products/{id}/variants 200 {ms}ms trace={trace}"),
            ("catalog-api", "info", "alert", "[RESOLVED] CatalogErrorRateHigh error_rate=0.2%"),
            ("api-gateway", "info", "alert", "[RESOLVED] GatewayUpstream5xx upstream=catalog-api"),
            ("cart-service", "info", "log", "GET /v1/cart/{id} 200 {ms}ms trace={trace}"),
        ],
    },
    "runbook": {
        "Symptoms": "A sharp step change in 5xx rate for one service that lines up with a deploy. Stack traces all point at the same new code path. Downstream callers (gateway, cart) show correlated 500s or fall back to stale cache.",
        "Detection": "Alerts: <Service>ErrorRateHigh, GatewayUpstream5xx. The deploy annotation on the error-rate graph makes the correlation obvious. Canary analysis should have caught it; check whether the canary threshold was too loose or the affected endpoint received too little canary traffic.",
        "Diagnosis": "Pull the top exception signature from logs for the service in the last 15 minutes. If a single new stack frame dominates and the deploy is under an hour old, stop diagnosing and roll back. Root-cause analysis happens after the rollback.",
        "Mitigation": "Roll back to the previous version using the deploy tool: tigerlily-deploy rollback <service> --to <prev_version>. Do not hotfix forward during the incident. If the rollback is blocked by a schema migration, page the service lead.",
        "Verification": "Error rate returns to baseline within one rollout cycle (two to three minutes). Downstream 5xx alerts resolve. Spot-check the failing endpoint manually.",
        "Escalation": "Page the owning team. Open a SEV2 if error rate exceeds 10% or a SEV1 if checkout is affected.",
    },
    "root_cause": "A refactor moved variant pricing to the new price_history table but assumed every variant had at least one history row. Roughly 8% of variants, mostly newly created ones, had no row yet, and the lookup dereferenced a null result. Canary analysis passed because the 10% canary slice received few requests for those variants in its five-minute window.",
    "contributing": [
        "The backfill migration for price_history was scheduled to run after the code deploy rather than before.",
        "Canary promotion used an error-rate threshold of 5%, which the canary stayed under during its short window.",
        "Unit tests covered variants with history but no test covered a missing-history variant.",
    ],
    "impact": "Product detail and variant endpoints returned 500 for about {impact_pct}% of requests over {impact_min} minutes. Cart pages that resolve product data also failed for the same window.",
    "action_items": [
        "Fall back to the variant's base price when no price_history row exists.",
        "Order data backfills before dependent code deploys in the release checklist.",
        "Lower canary error-rate threshold to 1% and lengthen the observation window to 15 minutes.",
    ],
    "issues": [
        {"repo": "tigerlily/catalog-api", "title": "NPE in PricingResolver when variant has no price_history row",
         "labels": ["bug", "sev2", "postmortem-action-item"],
         "body": "Cause of {incident_id}. PricingResolver.resolve assumes a non-empty history list. About 8% of variants have none (created after the last backfill).\n\nFix: fall back to variant.base_price and log at debug. Add a unit test for the empty case. Backfill should run before the next deploy of this path."},
        {"repo": "tigerlily/catalog-api", "title": "Canary promotion threshold too permissive (5% error rate, 5 min)",
         "labels": ["postmortem-action-item", "ci-cd"],
         "body": "The canary during {incident_id} ran at roughly 3% error rate and was promoted. Propose 1% over 15 minutes, and require a minimum request count per critical endpoint."},
    ],
    "questions": [
        ("catalog api returning 500 errors right after a deploy", "semantic"),
        ("NullPointerException PricingResolver", "keyword"),
        ("how do I roll back a bad deploy", "semantic"),
        ("canary passed but production had errors", "semantic"),
        ("price_history missing variant", "keyword"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "dns_resolution_failure",
    "title": "Cluster DNS failures causing intermittent upstream timeouts",
    "primary": "api-gateway",
    "services": ["api-gateway", "checkout-api", "payments", "search-api"],
    "error_code": "DNS_NXDOMAIN",
    "trigger": "infra",
    "duration": (30, 80),
    "phases": {
        "precursor": [
            ("api-gateway", "warning", "log", "DNS resolution for payments.svc.cluster.local took {slow_ms}ms"),
            ("api-gateway", "info", "k8s_event", "Pod coredns-{sha4} on {node}: container coredns restarted (reason=Completed) during node maintenance"),
            ("api-gateway", "warning", "log", "DNS resolution for search-api.svc.cluster.local took {slow_ms}ms"),
        ],
        "onset": [
            ("api-gateway", "error", "log", "dial tcp: lookup payments.svc.cluster.local on 10.96.0.10:53: no such host (NXDOMAIN) trace={trace}"),
            ("checkout-api", "error", "log", "GET /v1/checkout/{id}/tax 500 unhandled error: lookup inventory.svc.cluster.local: server misbehaving trace={trace}"),
            ("api-gateway", "warning", "log", "upstream payments health check failed 1/3 (timeout after 2s), still in rotation"),
            ("search-api", "warning", "log", "retrying call to postgres attempt 2/3 after timeout {ms}ms (dns) trace={trace}"),
        ],
        "peak": [
            ("api-gateway", "error", "log", "dial tcp: lookup payments.svc.cluster.local on 10.96.0.10:53: no such host (NXDOMAIN) trace={trace}"),
            ("api-gateway", "error", "log", "dial tcp: lookup checkout-api.svc.cluster.local on 10.96.0.10:53: read udp timeout trace={trace}"),
            ("checkout-api", "error", "log", "POST /v1/checkout 502 upstream payments connection failed: lookup payments.svc.cluster.local: i/o timeout trace={trace}"),
            ("payments", "info", "log", "served {n} requests in last 60s, p50=38ms p99=160ms error_rate=0.1%"),
            ("api-gateway", "critical", "alert", "[FIRING] GatewayUpstream5xx upstream=payments rate={pct}%"),
            ("api-gateway", "critical", "alert", "[FIRING] CoreDNSErrorRate nxdomain_rate={pct}% servfail_rate={n2}%"),
            ("api-gateway", "warning", "k8s_event", "Pod coredns-{sha4} on {node}: readiness probe failed: HTTP probe failed with statuscode: 503"),
            ("search-api", "error", "log", "GET /v1/search 504 upstream catalog-api timed out (dns lookup) trace={trace}"),
        ],
        "mitigation": [
            ("api-gateway", "info", "log", "incident {incident_id}: {oncall} found coredns running 1/3 replicas after node pool rotation, scaling to 3 and adding pod anti-affinity"),
            ("api-gateway", "info", "k8s_event", "Deployment coredns: scaled replicas 1 -> 3"),
            ("api-gateway", "info", "k8s_event", "Pod coredns-{sha4} scheduled on {node}, Ready"),
            ("api-gateway", "info", "log", "enabled NodeLocal DNSCache on all node pools (manual: {oncall})"),
        ],
        "recovery": [
            ("api-gateway", "info", "log", "upstream health check passed for payments (12/12 healthy)"),
            ("api-gateway", "info", "alert", "[RESOLVED] GatewayUpstream5xx upstream=payments"),
            ("api-gateway", "info", "alert", "[RESOLVED] CoreDNSErrorRate nxdomain_rate=0.0%"),
            ("checkout-api", "info", "log", "POST /v1/checkout 201 {ms}ms trace={trace}"),
        ],
    },
    "runbook": {
        "Symptoms": "Intermittent 502 and 504 errors across many unrelated services at once. Error messages mention 'no such host', 'server misbehaving', 'i/o timeout' on .svc.cluster.local names. The services being called look perfectly healthy in their own logs. Errors are bursty rather than constant.",
        "Detection": "Alerts: CoreDNSErrorRate, GatewayUpstream5xx firing for several upstreams together. Dashboard: Platform > Cluster DNS. If many services fail at the same time with no shared deploy, suspect DNS or networking before application code.",
        "Diagnosis": "kubectl -n kube-system get pods -l k8s-app=kube-dns. Fewer ready replicas than expected, or all replicas on one node, is the usual finding after node maintenance. Check CoreDNS logs for SERVFAIL or upstream timeouts. From a debug pod, run dig payments.svc.cluster.local repeatedly to see the failure rate.",
        "Mitigation": "Scale CoreDNS back to at least 3 replicas spread across nodes. Restart CoreDNS pods if they are ready but returning SERVFAIL. Enable NodeLocal DNSCache if it is not on. Application teams should not change anything during the incident; their retries will succeed once DNS recovers.",
        "Verification": "dig from a debug pod succeeds 100 times in a row. CoreDNSErrorRate resolves. Gateway 5xx returns to baseline within two minutes.",
        "Escalation": "Page platform-infra. If the cluster network itself is degraded (CNI errors, node NotReady), page the cloud provider support line.",
    },
    "root_cause": "A node pool rotation for a kernel patch drained nodes one at a time. CoreDNS had three replicas but no pod anti-affinity, and after the rotation two of them landed on the same node, which was then drained. For about 40 minutes a single CoreDNS replica served the whole cluster, dropped queries under load, and returned NXDOMAIN and SERVFAIL for valid service names.",
    "contributing": [
        "CoreDNS lacked pod anti-affinity and a PodDisruptionBudget.",
        "NodeLocal DNSCache was not enabled, so every lookup went to the central replicas.",
        "Go services cached negative DNS results briefly, amplifying single failures into short outages.",
    ],
    "impact": "Roughly {impact_pct}% of API requests failed intermittently across checkout, search, and cart for {impact_min} minutes. No data loss.",
    "action_items": [
        "Add pod anti-affinity and a PodDisruptionBudget (minAvailable 2) to CoreDNS.",
        "Enable NodeLocal DNSCache on all node pools.",
        "Add CoreDNS ready-replica count to the pre-flight checks of the node rotation runbook.",
    ],
    "issues": [
        {"repo": "tigerlily/db-ops", "title": "CoreDNS needs anti-affinity and PDB so node rotation cannot drain it to one replica",
         "labels": ["bug", "sev2", "postmortem-action-item", "kubernetes"],
         "body": "During {incident_id} the kernel-patch rotation left 1/3 CoreDNS replicas serving the cluster. Add requiredDuringScheduling anti-affinity on hostname and a PDB with minAvailable: 2. Also enable NodeLocal DNSCache."},
    ],
    "questions": [
        ("intermittent timeouts across many services at the same time", "semantic"),
        ("no such host svc.cluster.local", "keyword"),
        ("coredns", "keyword"),
        ("everything started failing during node maintenance", "semantic"),
        ("NXDOMAIN errors calling internal services", "hybrid"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "kafka_consumer_lag",
    "title": "Order fulfillment backlog from Kafka consumer lag",
    "primary": "order-service",
    "services": ["order-service", "kafka", "notifications"],
    "error_code": "KAFKA_LAG",
    "trigger": "capacity",
    "duration": (90, 240),
    "phases": {
        "precursor": [
            ("order-service", "info", "log", "consumed {n} messages from orders.created partition {partition} offset={offset} lag={lag_small}"),
            ("order-service", "warning", "log", "processing rate dropped to {n}/s from baseline {baseline}/s"),
            ("kafka", "info", "log", "kafka: partition orders.created-{partition} leader elected broker-2"),
        ],
        "onset": [
            ("order-service", "warning", "log", "consumer lag on orders.created partition {partition} is {lag} messages (threshold 1000)"),
            ("order-service", "warning", "log", "job order-fulfillment took {sec}s, exceeding expected duration of 120s"),
            ("order-service", "warning", "log", "inventory reserve call p99 {slow_ms}ms, holding partition {partition} consumer"),
            ("kafka", "warning", "alert", "[FIRING] KafkaConsumerLagHigh group=order-service topic=orders.created lag={lag}"),
        ],
        "peak": [
            ("order-service", "warning", "log", "consumer lag on orders.created partition {partition} is {lag_big} messages (threshold 1000)"),
            ("order-service", "error", "log", "order {id} fulfillment delayed {n} minutes, still queued at offset {offset}"),
            ("notifications", "warning", "log", "order confirmation emails delayed: {n} pending in notifications.email, oldest {n2} min"),
            ("kafka", "critical", "alert", "[FIRING] KafkaConsumerLagCritical group=order-service topic=orders.created lag={lag_big} oldest_message_age={n}m"),
            ("order-service", "warning", "log", "consumer group order-service rebalance complete, assigned partitions [{partition}], {n2} rebalances in 10m"),
            ("kafka", "warning", "log", "kafka: under-replicated partitions: 0 for topic orders.created, consumer group order-service lag {lag_big}"),
            ("order-service", "warning", "k8s_event", "HorizontalPodAutoscaler order-service: unable to scale, max replicas 6 reached"),
        ],
        "mitigation": [
            ("order-service", "info", "log", "incident {incident_id}: {oncall} raised HPA max 6 -> 16 and consumer concurrency 4 -> 8"),
            ("order-service", "info", "k8s_event", "Deployment order-service: scaled replicas 6 -> 16"),
            ("kafka", "info", "log", "kafka: increased partitions for orders.created from 6 to 16 (manual: {oncall})"),
            ("order-service", "info", "log", "consumer group order-service rebalance complete, assigned partitions [{partition}]"),
        ],
        "recovery": [
            ("order-service", "info", "log", "consumed {n} messages from orders.created partition {partition} offset={offset} lag={lag_small}"),
            ("kafka", "info", "alert", "[RESOLVED] KafkaConsumerLagCritical group=order-service lag=340"),
            ("kafka", "info", "alert", "[RESOLVED] KafkaConsumerLagHigh group=order-service lag=120"),
            ("notifications", "info", "log", "job email-dispatch completed: processed {n} records in {sec}s, backlog cleared"),
        ],
    },
    "runbook": {
        "Symptoms": "Orders are accepted but fulfillment and confirmation emails lag by many minutes. Consumer lag on orders.created climbs steadily. The consumer group may rebalance repeatedly. Nothing errors; it is a throughput problem.",
        "Detection": "Alerts: KafkaConsumerLagHigh (warning), KafkaConsumerLagCritical (oldest message age over 10 minutes). Dashboard: Fulfillment > Order pipeline > lag by partition and processing rate.",
        "Diagnosis": "Determine whether producers sped up (a sale, a bot) or consumers slowed down (a slow downstream such as inventory reserve, a slow DB, GC pauses). Compare messages-in per second with messages-processed per second. Check whether the HPA is pinned at max replicas. Note that consumer replicas beyond the partition count do nothing; 6 partitions means at most 6 active consumers.",
        "Mitigation": "If consumers are slow because of a downstream, fix or bypass the downstream first. Otherwise scale: raise HPA max, raise per-consumer concurrency, and if partitions are the ceiling, add partitions (this is irreversible and changes key-to-partition mapping, so coordinate with the service owner). Communicate the delay to support so customers are told.",
        "Verification": "Lag trending down consistently for ten minutes. Oldest message age under two minutes. Email backlog drained.",
        "Escalation": "Page fulfillment on-call. If lag exceeds retention risk (millions of messages), page data-infra to extend topic retention before offsets expire.",
    },
    "root_cause": "A flash sale roughly tripled order volume. order-service was capped at 6 replicas by its HPA and orders.created had only 6 partitions, so throughput could not scale beyond 6 concurrent consumers. Each message also made a synchronous inventory reserve call whose latency rose under the same load, cutting per-consumer throughput in half.",
    "contributing": [
        "Partition count had not been revisited since launch and matched the original replica count.",
        "The HPA maximum was sized for normal traffic with no headroom for promotions.",
        "Inventory reserve was called synchronously inside the consumer loop.",
    ],
    "impact": "Order fulfillment and confirmation emails were delayed by up to {impact_min} minutes for approximately {impact_orders} orders. No orders were lost.",
    "action_items": [
        "Increase orders.created to 32 partitions and set HPA max to 32.",
        "Make the inventory reserve call asynchronous with its own retry topic.",
        "Add a pre-promotion capacity checklist owned by fulfillment.",
    ],
    "issues": [
        {"repo": "tigerlily/order-service", "title": "Consumer throughput capped by 6 partitions on orders.created",
         "labels": ["postmortem-action-item", "kafka", "capacity"],
         "body": "During {incident_id} lag hit six figures because we could not run more than 6 consumers. Increase to 32 partitions (coordinate key hashing change with order-status-sync) and lift the HPA max."},
        {"repo": "tigerlily/order-service", "title": "Move inventory reserve out of the consumer hot path",
         "labels": ["enhancement", "postmortem-action-item"],
         "body": "The synchronous reserve call doubled per-message time under load in {incident_id}. Publish to inventory.reserve-requested and let inventory reply on a result topic."},
    ],
    "questions": [
        ("orders are taking forever to get confirmation emails", "semantic"),
        ("KafkaConsumerLagCritical", "keyword"),
        ("consumer lag growing during a sale", "hybrid"),
        ("why can't we scale consumers past six replicas", "semantic"),
        ("orders.created partition lag", "keyword"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "redis_eviction_storm",
    "title": "Redis eviction storm causing cart data loss",
    "primary": "redis-cache",
    "services": ["redis-cache", "cart-service"],
    "error_code": "REDIS_MAXMEMORY",
    "trigger": "capacity",
    "duration": (30, 90),
    "phases": {
        "precursor": [
            ("redis-cache", "info", "log", "redis: {n}k keys, {mb}MB used of 4096MB, hit_rate=98.{n2}%, evicted_keys=0"),
            ("redis-cache", "warning", "log", "redis: used_memory {pct}% of maxmemory, largest keyspace cart:* {n}k keys avg ttl {n2}h"),
            ("cart-service", "info", "log", "feature flag snapshot refreshed, 42 flags loaded from config service (cart-ttl-extension=on)"),
        ],
        "onset": [
            ("redis-cache", "warning", "log", "redis: used_memory reached maxmemory 4096MB, policy allkeys-lru evicting"),
            ("redis-cache", "warning", "log", "redis: evicted_keys {n} in last 60s"),
            ("cart-service", "warning", "log", "cart {id} not found in redis, rebuilding from postgres carts table ({ms}ms) trace={trace}"),
            ("redis-cache", "warning", "alert", "[FIRING] RedisMemoryHigh instance=cache-primary used=99% maxmemory=4096MB"),
        ],
        "peak": [
            ("redis-cache", "warning", "log", "redis: evicted_keys {n_big} in last 60s, hit_rate={pct}%"),
            ("cart-service", "error", "log", "GET /v1/cart/{id} 404 cart missing after eviction, no postgres backup row (guest cart) trace={trace}"),
            ("cart-service", "warning", "log", "cart rebuild rate {n}/s, postgres carts table p99 {slow_ms}ms"),
            ("cart-service", "error", "log", "POST /v1/cart/{id}/items 409 cart version mismatch after cache eviction trace={trace}"),
            ("redis-cache", "critical", "alert", "[FIRING] RedisEvictionRateHigh instance=cache-primary evictions_per_min={n_big}"),
            ("cart-service", "critical", "alert", "[FIRING] CartNotFoundRateHigh rate={pct}% threshold=1%"),
            ("postgres", "warning", "log", "duration: {slow_ms}.412 ms  statement: SELECT ... FROM carts WHERE ... (slow query, >1000ms)"),
        ],
        "mitigation": [
            ("cart-service", "info", "log", "incident {incident_id}: {oncall} disabled flag cart-ttl-extension (was extending guest cart TTL 2h -> 30d)"),
            ("redis-cache", "info", "log", "redis: maxmemory raised 4096MB -> 8192MB (manual: {oncall})"),
            ("redis-cache", "info", "log", "redis: SCAN + EXPIRE applied to {n}k cart:* keys with ttl > 48h, set to 48h"),
        ],
        "recovery": [
            ("redis-cache", "info", "log", "redis: {n}k keys, {mb}MB used of 8192MB, hit_rate=97.{n2}%, evicted_keys=0"),
            ("redis-cache", "info", "alert", "[RESOLVED] RedisEvictionRateHigh evictions_per_min=0"),
            ("cart-service", "info", "alert", "[RESOLVED] CartNotFoundRateHigh rate=0.1%"),
            ("cart-service", "info", "log", "GET /v1/cart/{id} 200 {ms}ms cache=hit trace={trace}"),
        ],
    },
    "runbook": {
        "Symptoms": "Shoppers report empty carts. cart-service logs show cache misses, rebuilds, and 404s for guest carts. Redis used_memory sits at maxmemory and evicted_keys climbs. Postgres load rises as carts are rebuilt.",
        "Detection": "Alerts: RedisMemoryHigh, RedisEvictionRateHigh, CartNotFoundRateHigh. Dashboard: Storefront > Cart > cache hit rate, and Data > Redis > memory and evictions.",
        "Diagnosis": "Run INFO memory and INFO stats on the cache primary. If evicted_keys is rising, find what grew: redis-cli --bigkeys or the keyspace panel by prefix. Correlate with recent flag flips or deploys that changed TTLs or added a new key family. Guest carts live only in Redis, so their eviction is data loss.",
        "Mitigation": "Stop the growth first (revert the flag or deploy that changed TTLs). Raise maxmemory if the instance has headroom. Reduce TTL on the offending prefix with a SCAN loop rather than FLUSH. Do not switch eviction policy to noeviction during an incident; writes will start failing instead.",
        "Verification": "evicted_keys stays at zero for ten minutes. Cache hit rate above 95%. CartNotFoundRateHigh resolves.",
        "Escalation": "Page data-infra for Redis capacity changes. Page storefront for the application side.",
    },
    "root_cause": "A feature flag extended guest cart TTL from 2 hours to 30 days to improve return-visit conversion. Guest carts are the largest keyspace in the shared cache, and with the longer TTL the working set grew past maxmemory within a day. The allkeys-lru policy then evicted active carts along with stale ones, and guest carts have no persistent copy.",
    "contributing": [
        "Guest carts were stored only in Redis, so eviction meant loss.",
        "The flag change was treated as a product experiment and did not go through capacity review.",
        "The shared cache mixed session, cart, and catalog keys with a single eviction policy.",
    ],
    "impact": "Approximately {impact_orders} guest carts were lost and {impact_pct}% of cart reads returned 404 for {impact_min} minutes. Logged-in carts were rebuilt from Postgres with elevated latency.",
    "action_items": [
        "Persist guest carts to Postgres with a 30-day retention job.",
        "Split cart keys into a dedicated Redis instance with volatile-lru.",
        "Require capacity review for flags that change TTLs or key cardinality.",
    ],
    "issues": [
        {"repo": "tigerlily/cart-service", "title": "Guest carts exist only in Redis and are lost on eviction",
         "labels": ["bug", "sev2", "postmortem-action-item", "data-loss"],
         "body": "In {incident_id} the allkeys-lru policy evicted live guest carts. Write guest carts through to the carts table (nullable user_id) and rebuild from there on cache miss, same as logged-in carts."},
        {"repo": "tigerlily/db-ops", "title": "Dedicated Redis instance for cart keyspace",
         "labels": ["postmortem-action-item", "redis", "capacity"],
         "body": "Carts share cache-primary with sessions and catalog fragments. Move cart:* to its own instance with volatile-lru so eviction pressure from one keyspace cannot affect the others. From {incident_id}."},
    ],
    "questions": [
        ("customers say their shopping cart is empty", "semantic"),
        ("redis evicted_keys spike", "keyword"),
        ("cache hit rate dropped after a feature flag change", "semantic"),
        ("allkeys-lru", "keyword"),
        ("what happened when we extended guest cart TTL", "hybrid"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "disk_full_wal",
    "title": "Postgres WAL volume filling up",
    "primary": "postgres",
    "services": ["postgres", "order-service", "checkout-api"],
    "error_code": "PG_53100",
    "trigger": "capacity",
    "duration": (45, 120),
    "phases": {
        "precursor": [
            ("postgres", "warning", "log", "replication slot replica_eu_central_1 inactive, retained WAL {n}GB"),
            ("postgres", "warning", "log", "wal archiving: archive command failed for segment {lsn}: object-store returned 403 (credentials rotated?)"),
            ("postgres", "warning", "alert", "[FIRING] PostgresDiskUsageHigh volume=pg_wal used={pct}% (warning 80%)"),
        ],
        "onset": [
            ("postgres", "warning", "log", "pg_wal directory {n}GB, {n2}k segments pending archive, disk {pct}% used"),
            ("postgres", "warning", "log", "checkpoints are occurring too frequently ({n} seconds apart), consider increasing max_wal_size"),
            ("postgres", "error", "log", "wal archiving: archive command failed {n} consecutive times for segment {lsn}"),
        ],
        "peak": [
            ("postgres", "critical", "log", "PANIC: could not write to file \"pg_wal/xlogtemp.{id}\": No space left on device"),
            ("postgres", "error", "log", "ERROR: could not extend file \"base/16384/{id}\": No space left on device (SQLSTATE 53100)"),
            ("order-service", "error", "log", "job order-fulfillment failed: ERROR: could not extend file: No space left on device"),
            ("checkout-api", "error", "log", "POST /v1/checkout/{id}/confirm 500 database error: disk full (53100) trace={trace}"),
            ("postgres", "critical", "alert", "[FIRING] PostgresDiskUsageCritical volume=pg_wal used=100%"),
            ("postgres", "critical", "alert", "[FIRING] PostgresPrimaryDown instance=tigerlily-primary"),
            ("checkout-api", "critical", "alert", "[FIRING] CheckoutErrorRateHigh error_rate={pct}% threshold=2% window=5m"),
            ("postgres", "info", "log", "database system was interrupted; last known up at {date}"),
        ],
        "mitigation": [
            ("postgres", "info", "log", "incident {incident_id}: {oncall} dropped inactive replication slot replica_eu_central_1, freeing {n}GB"),
            ("postgres", "info", "log", "wal archiving: credentials refreshed, archive command succeeded for segment {lsn}"),
            ("postgres", "info", "log", "pg_wal volume expanded 200GB -> 400GB online (manual: {oncall})"),
            ("postgres", "info", "log", "database system is ready to accept connections"),
        ],
        "recovery": [
            ("postgres", "info", "log", "checkpoint complete: wrote {n} buffers ({pct}%), {sec}s total"),
            ("postgres", "info", "log", "wal archiving: archived segment {lsn}, backlog cleared"),
            ("postgres", "info", "alert", "[RESOLVED] PostgresPrimaryDown instance=tigerlily-primary"),
            ("postgres", "info", "alert", "[RESOLVED] PostgresDiskUsageCritical volume=pg_wal used=31%"),
            ("checkout-api", "info", "alert", "[RESOLVED] CheckoutErrorRateHigh error_rate=0.2%"),
        ],
    },
    "runbook": {
        "Symptoms": "Writes fail with 'No space left on device' (SQLSTATE 53100). In the worst case the primary PANICs and restarts. Before that, disk usage on the WAL volume climbs steadily for hours or days while data volume stays flat.",
        "Detection": "Alerts: PostgresDiskUsageHigh at 80%, PostgresDiskUsageCritical at 95%, PostgresPrimaryDown. Dashboard: Data > Postgres > WAL size and archive lag. Also watch pg_replication_slots for inactive slots.",
        "Diagnosis": "WAL grows when something prevents it from being recycled: an inactive replication slot holding restart_lsn, a failing archive_command, or a long-running transaction. Run SELECT slot_name, active, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)) FROM pg_replication_slots. Check the log for archive failures. Check pg_stat_archiver.",
        "Mitigation": "Free space without deleting WAL files by hand. Drop or advance the inactive slot if the replica is gone for good. Fix the archive command (credentials, bucket permissions) so pending segments ship. If the disk is already full, expand the volume online first, then fix the cause. Never rm files from pg_wal.",
        "Verification": "pg_wal size shrinks after the next checkpoint. pg_stat_archiver last_archived_time is recent. Disk usage under 50%. Application error rates back to baseline.",
        "Escalation": "Page data-infra immediately at the critical alert. If the primary does not come back after restart, begin failover to the standby per the failover runbook.",
    },
    "root_cause": "Object-store credentials used by archive_command were rotated by a scheduled job, but the new secret was not propagated to the database host. WAL archiving failed silently for 6 days. At the same time an old replication slot for a decommissioned eu-central-1 replica remained active in the catalog, pinning WAL. The 200GB WAL volume filled, and the primary panicked on the next write.",
    "contributing": [
        "PostgresDiskUsageHigh at 80% fired to Slack only.",
        "No alert existed on pg_stat_archiver failure count.",
        "The replica decommission runbook did not include dropping its replication slot.",
        "Credential rotation did not include the database hosts in its propagation list.",
    ],
    "impact": "All writes failed and the primary was unavailable for {impact_min} minutes. Checkout, orders, and inventory updates failed during that window. No committed data was lost.",
    "action_items": [
        "Alert on pg_stat_archiver.failed_count increasing and on any inactive replication slot older than 1 hour.",
        "Add slot cleanup to the replica decommission runbook.",
        "Include database hosts in the credential rotation propagation and add a post-rotation archive test.",
        "Page on WAL volume at 80%.",
    ],
    "issues": [
        {"repo": "tigerlily/db-ops", "title": "Alert on WAL archive failures and inactive replication slots",
         "labels": ["postmortem-action-item", "alerting", "database"],
         "body": "Both root causes of {incident_id} were visible in catalog views for days. Add: pg_stat_archiver failed_count delta > 0 for 15m (page), and pg_replication_slots active=false for > 1h (page)."},
        {"repo": "tigerlily/db-ops", "title": "Credential rotation job does not update archive_command secret on db hosts",
         "labels": ["bug", "sev1", "postmortem-action-item", "security"],
         "body": "The rotation job updated the vault and app deployments but not the database hosts, so archive_command used a revoked key for 6 days before {incident_id}. Add db hosts to propagation and verify with a test archive after rotation."},
    ],
    "questions": [
        ("postgres ran out of disk space", "semantic"),
        ("No space left on device", "keyword"),
        ("why did WAL keep growing", "semantic"),
        ("inactive replication slot retained WAL", "hybrid"),
        ("archive command failed", "keyword"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "memory_leak_slow",
    "title": "Slow memory leak in search-api causing periodic restarts",
    "primary": "search-api",
    "services": ["search-api", "api-gateway"],
    "error_code": "OOMKilled",
    "trigger": "deploy",
    "trigger_service": "search-api",
    "trigger_summary": "Add per-request facet cache to speed up repeated filter queries",
    "duration": (600, 1800),
    "phases": {
        "precursor": [
            ("search-api", "info", "log", "started {pod} version={version} commit={sha} listening on :8080"),
            ("search-api", "info", "log", "facet cache enabled, max_entries=unbounded, hit_rate={pct}%"),
            ("search-api", "warning", "log", "GC pause {ms}ms on {pod} exceeds 200ms budget"),
        ],
        "onset": [
            ("search-api", "warning", "log", "worker {pod} memory {mb}MB approaching limit 1536MB, up {n}MB since start"),
            ("search-api", "warning", "log", "GC pause {slow_ms}ms on {pod} exceeds 200ms budget, heap {mb}MB"),
            ("search-api", "warning", "log", "GET /v1/search 200 {slow_ms}ms exceeds slow-request threshold (1000ms) trace={trace}"),
        ],
        "peak": [
            ("search-api", "critical", "k8s_event", "Pod {pod}: container search-api terminated reason=OOMKilled exitCode=137"),
            ("search-api", "info", "log", "started {pod} version={version} commit={sha} listening on :8080"),
            ("search-api", "warning", "log", "worker {pod} memory {mb_high}MB approaching limit 1536MB, up {n}MB since start ({n2}h uptime)"),
            ("api-gateway", "error", "log", "upstream search-api returned 502 for /v1/search, retried on next replica trace={trace}"),
            ("api-gateway", "warning", "log", "upstream search-api response time p99 {slow_ms}ms exceeds SLO 800ms"),
            ("search-api", "warning", "alert", "[FIRING] PodRestartsFrequent pod={pod} restarts_24h={n2}"),
            ("search-api", "warning", "alert", "[FIRING] SearchLatencyP99 p99={slow_ms}ms threshold=800ms"),
        ],
        "mitigation": [
            ("search-api", "info", "log", "incident {incident_id}: {oncall} identified unbounded facet cache growth via heap profile, deploying bounded LRU (10k entries)"),
            ("search-api", "info", "log", "started {pod} version={version_next} commit={sha} listening on :8080, facet cache max_entries=10000"),
        ],
        "recovery": [
            ("search-api", "info", "log", "worker {pod} memory {mb}MB stable over {n2}h, facet cache at 10000 entries hit_rate={pct}%"),
            ("search-api", "info", "alert", "[RESOLVED] PodRestartsFrequent pod={pod}"),
            ("search-api", "info", "alert", "[RESOLVED] SearchLatencyP99 p99=210ms"),
        ],
    },
    "runbook": {
        "Symptoms": "A service's memory climbs steadily from startup until it is OOMKilled, restarts, and climbs again. The sawtooth is visible over hours. Latency degrades toward the top of each cycle as GC works harder. Users see occasional 502s and slow searches rather than an outage.",
        "Detection": "Alerts: PodRestartsFrequent, <Service>LatencyP99. Dashboard: RSS by pod over 24h shows the sawtooth. Deploy annotations show where the slope changed.",
        "Diagnosis": "Take a heap profile from a pod near the top of its cycle (Python: py-spy dump or tracemalloc snapshot endpoint; Go: /debug/pprof/heap). The dominant growing allocation is the leak. Common causes: an unbounded cache or dict keyed on request data, listeners registered per request, or a global list that is appended and never trimmed. Compare with the deploy that changed the slope.",
        "Mitigation": "Buy time by raising the memory limit or scheduling a rolling restart before the cycle peaks. Then fix the leak: bound the cache with an LRU and TTL. Rolling back the offending deploy is also fine if the feature is not critical.",
        "Verification": "RSS flattens after warm-up and stays flat for several hours. No OOMKilled events over 24h. Latency p99 back under SLO.",
        "Escalation": "Owning team on-call. This is rarely a page unless restarts are frequent enough to cause user-visible errors.",
    },
    "root_cause": "A new per-request facet cache was keyed on the full filter string, including free-text query terms, and had no size bound or TTL. Every distinct search query added an entry that was never evicted. Memory grew at roughly 60MB per hour under production traffic until each pod hit its 1.5GB limit and was killed, every 18 to 22 hours.",
    "contributing": [
        "The cache was reviewed for correctness but not for bound or eviction.",
        "Staging traffic is repetitive and never grew the cache.",
        "A daily restart pattern was dismissed as 'normal Python' for a week.",
    ],
    "impact": "Search p99 latency exceeded SLO for about {impact_pct}% of the day over {impact_days} days, and each pod restart produced a brief burst of 502s. No outage.",
    "action_items": [
        "Bound the facet cache (LRU 10k entries, 5 minute TTL) and key it on the facet filter only, not the free-text query.",
        "Add a memory growth-rate alert (RSS slope over 6h) for all http_api services.",
        "Add a leak check to the search-api soak test.",
    ],
    "issues": [
        {"repo": "tigerlily/search-api", "title": "Unbounded facet cache leaks memory until OOMKilled",
         "labels": ["bug", "sev3", "postmortem-action-item", "performance"],
         "body": "Root cause of {incident_id}. FacetCache is a plain dict keyed on the full query string. Replace with an LRU (cachetools.TTLCache maxsize=10000 ttl=300) keyed on the sorted facet filters only."},
    ],
    "questions": [
        ("search api memory keeps growing until it restarts", "semantic"),
        ("sawtooth memory pattern", "semantic"),
        ("PodRestartsFrequent search-api", "keyword"),
        ("unbounded cache memory leak", "hybrid"),
        ("search latency slowly getting worse over the day", "semantic"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "processor_rate_limit",
    "title": "Payment processor rate limiting during retry storm",
    "primary": "payments",
    "services": ["payments", "checkout-api", "billing"],
    "error_code": "HTTP_429",
    "trigger": "external",
    "duration": (30, 75),
    "phases": {
        "precursor": [
            ("payments", "warning", "log", "payment-processor responded 503 for authorize, retrying attempt 1/3 trace={trace}"),
            ("payments", "warning", "log", "payment-processor p99 {slow_ms}ms, elevated vs baseline 420ms"),
            ("payments", "warning", "log", "retrying call to payment-processor attempt 2/3 after timeout {ms}ms trace={trace}"),
        ],
        "onset": [
            ("payments", "error", "log", "payment-processor responded 429 Too Many Requests for authorize, Retry-After=30 trace={trace}"),
            ("payments", "warning", "log", "retry rate to payment-processor {n}/s, {pct}% of outbound calls are retries"),
            ("checkout-api", "warning", "log", "retrying call to payments attempt 2/3 after timeout {ms}ms trace={trace}"),
            ("payments", "warning", "alert", "[FIRING] ProcessorErrorRateHigh processor=primary rate={pct}%"),
        ],
        "peak": [
            ("payments", "error", "log", "payment-processor responded 429 Too Many Requests for authorize, Retry-After=60 trace={trace}"),
            ("payments", "error", "log", "authorize failed after 3 attempts: 429 rate limited, returning PAYMENT_UNAVAILABLE trace={trace}"),
            ("checkout-api", "error", "log", "POST /v1/checkout/{id}/confirm 503 payment unavailable, customer asked to retry trace={trace}"),
            ("payments", "critical", "alert", "[FIRING] PaymentAuthorizationFailures rate={pct}% threshold=5%"),
            ("checkout-api", "critical", "alert", "[FIRING] CheckoutErrorRateHigh error_rate={pct}% threshold=2% window=5m"),
            ("payments", "warning", "log", "processor account rate limit: 200 req/s, current attempted {n}/s including retries from {n2} replicas"),
            ("billing", "warning", "log", "job settlement-reconcile: {n} authorizations in state UNKNOWN pending processor confirmation"),
        ],
        "mitigation": [
            ("payments", "info", "log", "incident {incident_id}: {oncall} enabled circuit breaker for payment-processor (open after 20% 429s, half-open 30s)"),
            ("payments", "info", "log", "circuit breaker for downstream payment-processor is open, failing fast for 30s"),
            ("payments", "info", "log", "retry policy changed: exponential backoff with jitter, honor Retry-After, max 2 attempts (manual: {oncall})"),
            ("payments", "info", "log", "circuit breaker for downstream payment-processor is half-open, probing"),
        ],
        "recovery": [
            ("payments", "info", "log", "circuit breaker for downstream payment-processor is closed, {n} successes in window"),
            ("payments", "info", "alert", "[RESOLVED] PaymentAuthorizationFailures rate=0.4%"),
            ("checkout-api", "info", "alert", "[RESOLVED] CheckoutErrorRateHigh error_rate=0.3%"),
            ("billing", "info", "log", "job settlement-reconcile completed: reconciled {n} UNKNOWN authorizations, 0 duplicates"),
        ],
    },
    "runbook": {
        "Symptoms": "Payment authorizations fail with 429 from the processor. It usually starts with a brief processor blip (503s or slow responses); our retries then multiply the request rate past the account limit and the processor throttles us for minutes after it has recovered. Checkout shows 'payment unavailable'.",
        "Detection": "Alerts: ProcessorErrorRateHigh, PaymentAuthorizationFailures, CheckoutErrorRateHigh. Dashboard: Payments > Processor > requests, retries, and 429s. Check the processor's status page.",
        "Diagnosis": "Look at the ratio of retries to first attempts in outbound processor calls. If retries dominate, we are amplifying the problem. Check whether the client honors Retry-After. Check the number of payments replicas: each has its own retry budget, and they multiply.",
        "Mitigation": "Open the circuit breaker so we stop hammering the processor, then let it half-open and probe. Reduce retries to a small budget with jittered backoff. If the processor remains degraded for long, switch to the secondary processor per the processor-failover runbook. Ask support to message affected customers that pending payments will settle.",
        "Verification": "429 rate at zero. Authorization success above 99%. Billing reconcile job reports zero authorizations stuck in UNKNOWN.",
        "Escalation": "Page payments-platform. Open a ticket with the processor if their status page shows an incident. SEV1 if checkout failure exceeds 10% for 10 minutes.",
    },
    "root_cause": "The payment processor had a two-minute partial outage. Our client retried each failed authorization three times with a fixed 500ms delay across 12 replicas, tripling our request rate at exactly the moment the processor was recovering. The processor's account-level rate limiter throttled us with 429s for the next 40 minutes, long after its own outage ended. The client treated 429 like any other error and kept retrying.",
    "contributing": [
        "Retries used fixed delay without jitter or exponential backoff.",
        "The client did not honor Retry-After.",
        "No circuit breaker existed for the processor.",
        "Per-replica retry budgets were not coordinated.",
    ],
    "impact": "Approximately {impact_pct}% of checkout attempts failed with 'payment unavailable' for {impact_min} minutes, roughly {impact_orders} orders. {impact_n} authorizations ended in UNKNOWN state and were reconciled by billing within two hours; no double charges.",
    "action_items": [
        "Implement exponential backoff with jitter and honor Retry-After in the processor client.",
        "Add a circuit breaker with a shared token bucket across replicas.",
        "Add a 429-specific alert that pages before authorization failures do.",
    ],
    "issues": [
        {"repo": "tigerlily/payments", "title": "Processor client retries amplify outages into rate limiting",
         "labels": ["bug", "sev1", "postmortem-action-item", "resilience"],
         "body": "In {incident_id} a 2-minute processor blip turned into 40 minutes of 429s because of our retry storm. Changes: jittered exponential backoff, honor Retry-After, max 2 retries, and a circuit breaker (open at 20% failure over 30s)."},
        {"repo": "tigerlily/payments", "title": "Shared outbound rate limiter for payment-processor across replicas",
         "labels": ["enhancement", "postmortem-action-item", "resilience"],
         "body": "Each payments replica has an independent view of outbound rate. A Redis token bucket sized to 80% of the processor's account limit would have prevented {incident_id} from escalating."},
    ],
    "questions": [
        ("payment processor returning 429", "keyword"),
        ("our retries made the outage worse", "semantic"),
        ("Retry-After", "keyword"),
        ("checkout says payment unavailable", "semantic"),
        ("retry storm against third party", "hybrid"),
    ],
},
]
