"""
Incident families, part 2 of 2. See families_a.py for the field reference.
"""

FAMILIES_B = [
# ---------------------------------------------------------------------------
{
    "key": "node_pressure_evictions",
    "title": "Kubernetes node memory pressure evicting pods",
    "primary": "api-gateway",
    "services": ["api-gateway", "notifications", "image-resizer", "scheduler"],
    "error_code": "K8S_EVICTED",
    "trigger": "infra",
    "duration": (40, 110),
    "phases": {
        "precursor": [
            ("api-gateway", "warning", "k8s_event", "Node {node}: MemoryPressure condition True, available 412Mi"),
            ("image-resizer", "info", "log", "job resize-product-images started run_id={id}, {n} images queued (bulk catalog import)"),
            ("image-resizer", "warning", "log", "worker {pod} memory {mb_high}MB approaching limit 3072MB"),
        ],
        "onset": [
            ("notifications", "warning", "k8s_event", "Pod {pod} on {node}: Evicted, The node was low on resource: memory. Container notifications was using {mb}Mi, request is 256Mi"),
            ("scheduler", "warning", "k8s_event", "Pod {pod} on {node}: Evicted, The node was low on resource: memory"),
            ("api-gateway", "warning", "k8s_event", "Node {node}: kubelet, Attempting to reclaim memory"),
            ("api-gateway", "warning", "alert", "[FIRING] NodeMemoryPressure node={node} available=380Mi"),
        ],
        "peak": [
            ("notifications", "warning", "k8s_event", "Pod {pod} on {node}: Evicted, The node was low on resource: memory"),
            ("api-gateway", "error", "k8s_event", "Pod {pod} on {node}: Evicted, The node was low on resource: memory. Container api-gateway was using {mb}Mi, request is 512Mi"),
            ("api-gateway", "warning", "k8s_event", "Pod {pod}: FailedScheduling, 0/12 nodes are available: 4 Insufficient memory, 8 node(s) had taint"),
            ("notifications", "warning", "log", "consumer group notifications rebalance complete, assigned partitions [{partition}], {n2} rebalances in 10m"),
            ("api-gateway", "critical", "alert", "[FIRING] DeploymentReplicasUnavailable deployment=api-gateway available={n2}/8"),
            ("api-gateway", "error", "log", "upstream checkout-api health check failed 2/3, replica {pod} evicted"),
            ("image-resizer", "warning", "log", "worker {pod} memory {mb_high}MB, no limit set, node allocatable exceeded"),
            ("scheduler", "error", "log", "job abandoned-cart-sweep failed: pod evicted mid-run, lock {id} not released"),
        ],
        "mitigation": [
            ("image-resizer", "info", "log", "incident {incident_id}: {oncall} paused bulk import and set memory limit 2Gi on image-resizer (was unlimited)"),
            ("api-gateway", "info", "k8s_event", "Node pool general-purpose: scaled 12 -> 16 nodes (manual: {oncall})"),
            ("api-gateway", "info", "k8s_event", "Pod {pod} scheduled on {node}, Ready"),
            ("api-gateway", "info", "k8s_event", "Node {node}: MemoryPressure condition False"),
        ],
        "recovery": [
            ("api-gateway", "info", "alert", "[RESOLVED] DeploymentReplicasUnavailable deployment=api-gateway available=8/8"),
            ("api-gateway", "info", "alert", "[RESOLVED] NodeMemoryPressure node={node}"),
            ("notifications", "info", "log", "worker {pod} heartbeat ok, queue_depth={n}"),
            ("scheduler", "info", "log", "job abandoned-cart-sweep completed: processed {n} records in {sec}s (stale lock cleared)"),
        ],
    },
    "runbook": {
        "Symptoms": "Pods across unrelated namespaces are Evicted with 'The node was low on resource: memory'. New pods fail scheduling with Insufficient memory. Deployments run below desired replicas. Services with few replicas see errors; services with many see latency.",
        "Detection": "Alerts: NodeMemoryPressure, DeploymentReplicasUnavailable, PodEvictedRate. Dashboard: Platform > Nodes > allocatable vs used, and pods without limits.",
        "Diagnosis": "kubectl get events --field-selector reason=Evicted -A. Find the node, then kubectl top pod on it sorted by memory. The culprit is almost always a pod with no memory limit that grew, or a burst of pods scheduled by requests alone. Look for a batch job or bulk import that started around the same time.",
        "Mitigation": "Stop or cap the pod that is consuming the node (set a limit, scale it down, pause the job). Add nodes if the pool is near allocatable. Evicted pods reschedule on their own once memory frees. Clear any locks held by evicted jobs.",
        "Verification": "MemoryPressure condition False on all nodes. All deployments at desired replicas. No new Evicted events for 15 minutes.",
        "Escalation": "Page platform-infra. Page the team owning the runaway workload.",
    },
    "root_cause": "image-resizer had no memory limit, only a request. A bulk catalog import queued 40k images and the resizer's per-image working memory grew to over 6GB on one node. The kubelet evicted lower-priority pods on that node, including api-gateway and notifications replicas, and the displaced pods could not be rescheduled because the pool was near allocatable.",
    "contributing": [
        "No LimitRange enforced default memory limits in the storefront namespace.",
        "api-gateway had the same PriorityClass as batch workers.",
        "The node pool autoscaler was set to a maximum that left no headroom for evictions.",
    ],
    "impact": "api-gateway ran at {impact_pct}% capacity for {impact_min} minutes, producing intermittent 502s. Notification delivery was delayed. The bulk import itself was paused and resumed later.",
    "action_items": [
        "Enforce a LimitRange with default memory limits in every namespace.",
        "Give api-gateway, checkout-api, and payments a higher PriorityClass than batch workloads.",
        "Cap image-resizer at 2Gi and make it process images in a streaming fashion.",
    ],
    "issues": [
        {"repo": "tigerlily/image-resizer", "title": "No memory limit; bulk imports consume the whole node",
         "labels": ["bug", "sev2", "postmortem-action-item", "kubernetes"],
         "body": "Root cause of {incident_id}. Set limits.memory=2Gi and stream image decoding rather than loading originals fully. Also reject originals over 40MB."},
        {"repo": "tigerlily/db-ops", "title": "Namespace LimitRange defaults and PriorityClass for tier-1 services",
         "labels": ["postmortem-action-item", "kubernetes", "reliability"],
         "body": "From {incident_id}: default container memory limit 1Gi via LimitRange in all namespaces; PriorityClass tier1-critical for api-gateway, checkout-api, payments, auth-service so the kubelet evicts batch pods first."},
    ],
    "questions": [
        ("pods getting evicted for memory", "semantic"),
        ("The node was low on resource: memory", "keyword"),
        ("FailedScheduling Insufficient memory", "keyword"),
        ("gateway replicas disappeared during a bulk import", "semantic"),
        ("which pod ate all the node memory", "semantic"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "crashloop_config",
    "title": "Notifications service CrashLoopBackOff from missing config",
    "primary": "notifications",
    "services": ["notifications", "kafka"],
    "error_code": "CrashLoopBackOff",
    "trigger": "deploy",
    "trigger_service": "notifications",
    "trigger_summary": "Switch email provider client to v2 API and read EMAIL_PROVIDER_V2_KEY from secrets",
    "duration": (20, 60),
    "phases": {
        "precursor": [
            ("notifications", "info", "log", "started {pod} version={version} commit={sha} concurrency=4"),
            ("notifications", "critical", "log", "fatal: required environment variable EMAIL_PROVIDER_V2_KEY is not set, exiting"),
        ],
        "onset": [
            ("notifications", "error", "k8s_event", "Pod {pod}: container notifications terminated reason=Error exitCode=1"),
            ("notifications", "warning", "k8s_event", "Pod {pod}: Back-off restarting failed container, restartCount={n2}"),
            ("notifications", "critical", "log", "fatal: required environment variable EMAIL_PROVIDER_V2_KEY is not set, exiting"),
        ],
        "peak": [
            ("notifications", "error", "k8s_event", "Pod {pod}: CrashLoopBackOff, restartCount={n2}"),
            ("notifications", "critical", "log", "fatal: required environment variable EMAIL_PROVIDER_V2_KEY is not set, exiting"),
            ("notifications", "critical", "alert", "[FIRING] PodCrashLooping pod={pod} namespace=growth restarts={n2}"),
            ("kafka", "warning", "log", "consumer lag on notifications.email partition {partition} is {lag} messages (threshold 1000)"),
            ("kafka", "warning", "alert", "[FIRING] KafkaConsumerLagHigh group=notifications topic=notifications.email lag={lag}"),
            ("notifications", "warning", "k8s_event", "Deployment notifications: rollout stalled, 0/4 new replicas available, progress deadline exceeded"),
        ],
        "mitigation": [
            ("notifications", "info", "log", "incident {incident_id}: {oncall} added EMAIL_PROVIDER_V2_KEY to sealed secret in growth namespace"),
            ("notifications", "info", "k8s_event", "Secret notifications-secrets updated, restarting deployment"),
            ("notifications", "info", "log", "started {pod} version={version} commit={sha} concurrency=4, email provider client v2 ready"),
        ],
        "recovery": [
            ("notifications", "info", "alert", "[RESOLVED] PodCrashLooping pod={pod}"),
            ("notifications", "info", "log", "job email-dispatch completed: processed {n} records in {sec}s, backlog cleared"),
            ("kafka", "info", "alert", "[RESOLVED] KafkaConsumerLagHigh group=notifications lag=8"),
        ],
    },
    "runbook": {
        "Symptoms": "A deployment's new pods start, log a fatal error within seconds, and exit. Kubernetes reports CrashLoopBackOff with growing restart counts. The rollout stalls. Because old pods were already replaced, the service is down rather than degraded.",
        "Detection": "Alerts: PodCrashLooping, DeploymentRolloutStalled. The deploy tool marks the deploy as failed after the progress deadline.",
        "Diagnosis": "kubectl logs --previous on a crashing pod shows the fatal line. Missing env vars, unreadable secrets, a config file with a syntax error, or an unreachable dependency at startup are the usual causes. Compare the new version's required config against the deployed ConfigMap and Secret.",
        "Mitigation": "If the fix is a one-line config addition, add it and let the rollout continue. Otherwise roll back to the previous version immediately and add the config before redeploying. Consider whether the rollout strategy should have kept old pods until new ones were ready (maxUnavailable: 0).",
        "Verification": "All replicas Ready with restartCount stable. Consumer lag draining. PodCrashLooping resolved.",
        "Escalation": "Owning team. Rarely needs infra unless the secret store itself is unavailable.",
    },
    "root_cause": "The deploy introduced a hard requirement on EMAIL_PROVIDER_V2_KEY, but the secret was added to staging only. In production the new binary exited at startup. The deployment used maxUnavailable 25% and maxSurge 25%, so within a minute all old pods were gone and every replica was in CrashLoopBackOff.",
    "contributing": [
        "Secrets are managed per environment by hand with no diff check in the pipeline.",
        "The rollout strategy allowed old pods to be terminated before new pods passed readiness.",
        "No startup config validation ran as a pre-deploy job.",
    ],
    "impact": "No emails or SMS were sent for {impact_min} minutes. Approximately {impact_orders} order confirmations and {impact_n} password resets were delayed, then delivered.",
    "action_items": [
        "Add a pipeline step that diffs required env vars in the image against each environment's ConfigMap and Secret keys.",
        "Set maxUnavailable: 0 for all consumer services.",
        "Fail the deploy automatically on the first CrashLoopBackOff instead of waiting for the progress deadline.",
    ],
    "issues": [
        {"repo": "tigerlily/notifications", "title": "Production missing EMAIL_PROVIDER_V2_KEY caused CrashLoopBackOff on deploy",
         "labels": ["bug", "sev2", "postmortem-action-item", "config"],
         "body": "From {incident_id}. Add a required-config manifest to the repo and a CI check that every environment's secret has the keys. Also set maxUnavailable: 0."},
    ],
    "questions": [
        ("notifications pods keep crashing right after start", "semantic"),
        ("CrashLoopBackOff", "keyword"),
        ("required environment variable is not set", "keyword"),
        ("no emails going out after a deploy", "semantic"),
        ("deploy broke because secret was missing in production", "hybrid"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "mtls_cert_mismatch",
    "title": "mTLS handshake failures between auth-service and user-profile",
    "primary": "auth-service",
    "services": ["auth-service", "user-profile"],
    "error_code": "TLS_UNKNOWN_CA",
    "trigger": "config",
    "duration": (25, 70),
    "phases": {
        "precursor": [
            ("user-profile", "info", "log", "service mesh sidecar: rotated workload certificate, issuer=mesh-ca-v2, expires in 24h"),
            ("auth-service", "info", "log", "service mesh sidecar: trust bundle contains 1 root (mesh-ca-v1)"),
        ],
        "onset": [
            ("auth-service", "error", "log", "GET /v1/users/{id} upstream user-profile: tls: failed to verify certificate: x509: certificate signed by unknown authority trace={trace}"),
            ("auth-service", "warning", "log", "retrying call to user-profile attempt 2/3 after TLS error trace={trace}"),
            ("user-profile", "warning", "log", "service mesh sidecar: {n} inbound handshakes rejected by peer (unknown_ca alert)"),
        ],
        "peak": [
            ("auth-service", "error", "log", "GET /v1/users/{id} upstream user-profile: tls: failed to verify certificate: x509: certificate signed by unknown authority trace={trace}"),
            ("auth-service", "error", "log", "POST /oauth/token 500 unable to load user profile for claims: upstream TLS failure trace={trace}"),
            ("auth-service", "critical", "alert", "[FIRING] AuthTokenErrorRate error_rate={pct}% threshold=1%"),
            ("auth-service", "critical", "alert", "[FIRING] UpstreamTLSFailures source=auth-service dest=user-profile rate={n}/s"),
            ("api-gateway", "error", "log", "upstream auth-service returned 500 for /oauth/token, retried on next replica (also 500) trace={trace}"),
            ("user-profile", "info", "log", "GET /v1/users/{id} 200 {ms}ms trace={trace}"),
            ("auth-service", "error", "log", "user login failed for {n} sessions in last minute: profile lookup unavailable"),
        ],
        "mitigation": [
            ("auth-service", "info", "log", "incident {incident_id}: {oncall} found auth-service trust bundle missing mesh-ca-v2 root (CA rotation rolled out to 60% of namespaces)"),
            ("auth-service", "info", "log", "service mesh sidecar: trust bundle updated, contains 2 roots (mesh-ca-v1, mesh-ca-v2)"),
            ("auth-service", "info", "k8s_event", "Deployment auth-service: rolling restart to pick up trust bundle"),
        ],
        "recovery": [
            ("auth-service", "info", "log", "GET /v1/users/{id} upstream user-profile 200 {ms}ms mtls=ok trace={trace}"),
            ("auth-service", "info", "alert", "[RESOLVED] AuthTokenErrorRate error_rate=0.1%"),
            ("auth-service", "info", "alert", "[RESOLVED] UpstreamTLSFailures source=auth-service dest=user-profile"),
        ],
    },
    "runbook": {
        "Symptoms": "One service cannot call another over the mesh: 'certificate signed by unknown authority' or 'unknown_ca' TLS alerts. The callee looks healthy and serves other callers fine. Symptoms appear during or shortly after a mesh CA rotation or a sidecar upgrade.",
        "Detection": "Alerts: UpstreamTLSFailures (per source/dest pair), plus the caller's own error-rate alert. Dashboard: Platform > Mesh > handshake failures by pair.",
        "Diagnosis": "Compare the trust bundle on the caller's sidecar with the issuer of the callee's workload certificate. During a CA rotation the new root must be in every trust bundle before any workload certificate is issued by the new CA. A partial rollout that rotates workload certs in some namespaces before trust bundles in others produces exactly this.",
        "Mitigation": "Push the new root into the caller's trust bundle (both roots must be present during rotation) and restart the caller's sidecars. Do not disable mTLS or set permissive mode on tier-1 services during the incident unless the CA infrastructure itself is broken.",
        "Verification": "Handshake failures for the pair drop to zero. Caller error rate resolves. Every sidecar in the mesh reports both roots in its bundle.",
        "Escalation": "Page platform-infra (mesh owners). Page identity if login is impacted for more than 10 minutes.",
    },
    "root_cause": "A mesh CA rotation was rolled out namespace by namespace. The identity namespace received the new root in its trust bundle, but a rollout ordering bug issued user-profile a workload certificate from mesh-ca-v2 before auth-service, in the same namespace, had restarted to load the updated bundle. auth-service rejected user-profile's certificate as signed by an unknown authority, and every login that needed profile claims failed.",
    "contributing": [
        "Trust bundle updates required a sidecar restart rather than hot reload.",
        "The rotation tooling did not verify bundle presence before issuing new-CA certificates.",
        "auth-service depends synchronously on user-profile for token claims.",
    ],
    "impact": "Roughly {impact_pct}% of login and token refresh attempts failed for {impact_min} minutes. Existing sessions with valid tokens were unaffected.",
    "action_items": [
        "Make trust bundle updates hot-reloadable in the sidecar.",
        "Add a pre-issuance check to the CA rotation tool that confirms every sidecar has the new root.",
        "Cache profile claims in auth-service for 10 minutes so a profile outage does not block token issuance.",
    ],
    "issues": [
        {"repo": "tigerlily/auth-service", "title": "Token issuance hard-depends on user-profile; cache claims",
         "labels": ["enhancement", "postmortem-action-item", "resilience"],
         "body": "During {incident_id} an mTLS problem between auth-service and user-profile blocked all logins. Cache the claims subset (display name, roles) for 10 minutes and serve stale on upstream failure."},
        {"repo": "tigerlily/db-ops", "title": "Mesh CA rotation must verify trust bundles before issuing new-CA workload certs",
         "labels": ["bug", "sev2", "postmortem-action-item", "security", "mesh"],
         "body": "Ordering bug behind {incident_id}. Add a gate: for each namespace, all sidecars must report the new root before any workload cert is re-issued."},
    ],
    "questions": [
        ("certificate signed by unknown authority", "keyword"),
        ("logins failing but user-profile looks healthy", "semantic"),
        ("mTLS broke during CA rotation", "hybrid"),
        ("unknown_ca alert between services", "keyword"),
        ("why did auth-service reject user-profile's certificate", "semantic"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "migration_lock",
    "title": "Schema migration lock blocking inventory writes",
    "primary": "inventory",
    "services": ["inventory", "postgres", "checkout-api"],
    "error_code": "PG_LOCK_TIMEOUT",
    "trigger": "deploy",
    "trigger_service": "inventory",
    "trigger_summary": "Migration 0142: add NOT NULL column warehouse_id with default to inventory_levels",
    "duration": (10, 35),
    "phases": {
        "precursor": [
            ("inventory", "info", "log", "migration 0142_add_warehouse_id starting on inventory_levels ({n}M rows)"),
            ("postgres", "info", "log", "connection authorized: user=migrator database=tigerlily ssl=on"),
        ],
        "onset": [
            ("postgres", "warning", "log", "lock wait on relation inventory_levels: waited {slow_ms}ms for RowExclusiveLock, blocked by AccessExclusiveLock (pid {id}, migrator)"),
            ("inventory", "warning", "log", "POST /v1/inventory/reserve 200 {slow_ms}ms exceeds slow-request threshold (1000ms) trace={trace}"),
            ("postgres", "warning", "log", "process {id} still waiting for RowExclusiveLock on relation inventory_levels after 5000.{ms} ms, {n} other processes waiting"),
        ],
        "peak": [
            ("inventory", "error", "log", "POST /v1/inventory/reserve 500 canceling statement due to lock timeout (SQLSTATE 55P03) trace={trace}"),
            ("postgres", "error", "log", "ERROR: canceling statement due to lock timeout  STATEMENT: UPDATE inventory_levels SET reserved = reserved + $1 WHERE ..."),
            ("checkout-api", "error", "log", "POST /v1/checkout/{id}/confirm 502 upstream inventory connection failed: reserve timed out trace={trace}"),
            ("inventory", "critical", "alert", "[FIRING] InventoryErrorRateHigh error_rate={pct}% threshold=2%"),
            ("postgres", "critical", "alert", "[FIRING] PostgresLockWaitsHigh relation=inventory_levels waiting={n}"),
            ("checkout-api", "critical", "alert", "[FIRING] CheckoutErrorRateHigh error_rate={pct}% threshold=2% window=5m"),
            ("postgres", "warning", "log", "active connections at {pct}% of max_connections, {n} waiting on inventory_levels"),
        ],
        "mitigation": [
            ("postgres", "info", "log", "incident {incident_id}: {oncall} cancelled migration backend pid {id} with pg_cancel_backend"),
            ("inventory", "info", "log", "migration 0142_add_warehouse_id aborted, transaction rolled back after {n} minutes"),
            ("postgres", "info", "log", "lock on relation inventory_levels released, {n} waiting processes proceeding"),
        ],
        "recovery": [
            ("inventory", "info", "log", "POST /v1/inventory/reserve 200 {ms}ms trace={trace}"),
            ("inventory", "info", "alert", "[RESOLVED] InventoryErrorRateHigh error_rate=0.2%"),
            ("postgres", "info", "alert", "[RESOLVED] PostgresLockWaitsHigh relation=inventory_levels waiting=0"),
            ("checkout-api", "info", "alert", "[RESOLVED] CheckoutErrorRateHigh error_rate=0.3%"),
        ],
    },
    "runbook": {
        "Symptoms": "Writes to one table stall then fail with lock timeouts (SQLSTATE 55P03). Reads may continue. A migration is running. Lock waits pile up and connections are consumed by waiting sessions, so other tables can be affected indirectly.",
        "Detection": "Alerts: PostgresLockWaitsHigh, the owning service's error-rate alert. Query: SELECT pid, wait_event_type, state, left(query, 80) FROM pg_stat_activity WHERE wait_event_type = 'Lock'.",
        "Diagnosis": "Find the blocker with SELECT pg_blocking_pids(pid) or the pg_locks join in the DBA snippets. If the blocker is the migrator role holding AccessExclusiveLock on a big table, the migration is doing a full rewrite (adding a column with a volatile default, changing a type, adding NOT NULL without a validated constraint) or is queued behind a long transaction and holding the lock while it waits.",
        "Mitigation": "Cancel the migration with pg_cancel_backend; use pg_terminate_backend if cancel does not work within 10 seconds. The table returns to its previous state. Rewrite the migration to be online: add the column nullable, backfill in batches, add a NOT VALID check constraint and validate separately, then set NOT NULL. Always set lock_timeout to a few seconds in migration sessions.",
        "Verification": "No processes waiting on the relation. Service error rate at baseline. Migration marked as not applied so it can be rerun safely.",
        "Escalation": "Page data-infra if the blocker cannot be identified or cancelled. Page the owning service team.",
    },
    "root_cause": "Migration 0142 added a NOT NULL column with a non-constant default to inventory_levels, a 40M-row table. On this Postgres version that forced a full table rewrite under AccessExclusiveLock. The migration ran without lock_timeout, so it acquired the lock and held it for the rewrite while every inventory reserve and release call queued behind it and then timed out.",
    "contributing": [
        "The migration linter did not flag volatile defaults as rewrite-triggering.",
        "Migrations ran with no lock_timeout or statement_timeout.",
        "The migration was applied during peak traffic rather than the low-traffic window.",
    ],
    "impact": "Inventory reservations failed for {impact_min} minutes, which blocked {impact_pct}% of checkouts. No inventory data was corrupted; the migration rolled back cleanly.",
    "action_items": [
        "Enforce lock_timeout = 5s and statement_timeout = 60s in the migrator role.",
        "Extend the migration linter (squawk) to flag NOT NULL with volatile default and type changes.",
        "Schedule migrations on tables over 1M rows in the 03:00 UTC window unless approved.",
    ],
    "issues": [
        {"repo": "tigerlily/inventory", "title": "Migration 0142 rewrote inventory_levels under AccessExclusiveLock",
         "labels": ["bug", "sev2", "postmortem-action-item", "database", "migration"],
         "body": "From {incident_id}. Rewrite as: ADD COLUMN warehouse_id int NULL; batched backfill; ADD CONSTRAINT ... CHECK (warehouse_id IS NOT NULL) NOT VALID; VALIDATE CONSTRAINT; SET NOT NULL. Run under lock_timeout=5s."},
        {"repo": "tigerlily/db-ops", "title": "Set lock_timeout and statement_timeout on the migrator role",
         "labels": ["postmortem-action-item", "database"],
         "body": "ALTER ROLE migrator SET lock_timeout = '5s'; ALTER ROLE migrator SET statement_timeout = '60s'. Would have turned {incident_id} into a failed migration instead of an outage."},
    ],
    "questions": [
        ("inventory writes blocked during a migration", "semantic"),
        ("canceling statement due to lock timeout", "keyword"),
        ("AccessExclusiveLock inventory_levels", "keyword"),
        ("how to add a NOT NULL column without locking the table", "semantic"),
        ("checkout failing because inventory reserve times out", "hybrid"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "cdn_origin_timeouts",
    "title": "CDN origin timeouts from image-resizer object store latency",
    "primary": "image-resizer",
    "services": ["image-resizer", "edge-proxy", "catalog-api"],
    "error_code": "HTTP_504",
    "trigger": "external",
    "duration": (30, 90),
    "phases": {
        "precursor": [
            ("image-resizer", "warning", "log", "object-store GET latency p99 {slow_ms}ms, baseline 90ms, region {region}"),
            ("image-resizer", "warning", "log", "retrying call to object-store attempt 2/3 after timeout {ms}ms trace={trace}"),
        ],
        "onset": [
            ("edge-proxy", "warning", "log", "upstream image-resizer response time p99 {slow_ms}ms exceeds SLO 800ms"),
            ("image-resizer", "error", "log", "GET /img/{id}/w800 504 origin fetch from object-store exceeded 10s trace={trace}"),
            ("edge-proxy", "warning", "log", "cdn: origin shield reports {pct}% cache miss for /img/*, origin latency {slow_ms}ms"),
        ],
        "peak": [
            ("edge-proxy", "error", "log", "route /img/{id}/w800 504 upstream image-resizer timed out after 30s trace={trace}"),
            ("image-resizer", "error", "log", "GET /img/{id}/w400 504 origin fetch from object-store exceeded 10s trace={trace}"),
            ("image-resizer", "warning", "log", "worker {pod} {n} in-flight origin fetches, queue depth {n2}, rejecting new requests with 503"),
            ("edge-proxy", "critical", "alert", "[FIRING] CDNOriginErrorRate path=/img/* rate={pct}% threshold=5%"),
            ("edge-proxy", "critical", "alert", "[FIRING] GatewayUpstream5xx upstream=image-resizer rate={pct}%"),
            ("catalog-api", "warning", "log", "product {id} primary image failed CDN health probe, serving placeholder"),
            ("image-resizer", "warning", "alert", "[FIRING] ObjectStoreLatencyHigh region={region} p99={slow_ms}ms"),
        ],
        "mitigation": [
            ("image-resizer", "info", "log", "incident {incident_id}: {oncall} pointed image-resizer at object-store replica bucket in us-west-2 (provider incident in {region})"),
            ("edge-proxy", "info", "log", "cdn: stale-if-error enabled for /img/* with 24h window (manual: {oncall})"),
            ("image-resizer", "info", "log", "object-store GET latency p99 {ms}ms, region us-west-2"),
        ],
        "recovery": [
            ("edge-proxy", "info", "alert", "[RESOLVED] CDNOriginErrorRate path=/img/* rate=0.2%"),
            ("edge-proxy", "info", "alert", "[RESOLVED] GatewayUpstream5xx upstream=image-resizer"),
            ("image-resizer", "info", "alert", "[RESOLVED] ObjectStoreLatencyHigh region={region}"),
            ("image-resizer", "info", "log", "GET /img/{id}/w800 200 {ms}ms cache=miss origin=us-west-2 trace={trace}"),
        ],
    },
    "runbook": {
        "Symptoms": "Product images fail to load or load slowly. CDN reports origin errors for /img/*. image-resizer logs show slow or timed-out fetches from the object store while CPU is idle. Other services are fine.",
        "Detection": "Alerts: CDNOriginErrorRate, ObjectStoreLatencyHigh, GatewayUpstream5xx for image-resizer. Check the cloud provider status page for the object store in the affected region.",
        "Diagnosis": "Compare object-store latency by region in the resizer metrics. If one region is slow and the provider status page confirms, this is external. If all regions are slow, check our own network egress and the resizer's connection pool to the store.",
        "Mitigation": "Fail over the resizer's origin bucket to the cross-region replica. Enable stale-if-error on the CDN for image paths so cached renditions keep serving. Shed load in the resizer with a bounded queue rather than letting requests pile up to 30s.",
        "Verification": "Origin error rate under 1%. Object-store p99 back under 200ms. Images load on product pages in synthetic checks.",
        "Escalation": "Page storefront for the resizer. Open a provider support case with request IDs. Communicate on status page if images are broken for more than 15 minutes.",
    },
    "root_cause": "The cloud provider's object storage in us-east-1 had a regional latency incident lasting about an hour. image-resizer fetched originals from a single-region bucket with a 10s timeout and no fallback, and the CDN's origin timeout of 30s meant each miss tied up a resizer worker for up to 30s. The worker pool saturated and healthy renditions were also delayed.",
    "contributing": [
        "The originals bucket had a cross-region replica that nothing was configured to use.",
        "stale-if-error was not enabled on the CDN for image paths.",
        "The resizer had no bounded queue or load shedding.",
    ],
    "impact": "Approximately {impact_pct}% of uncached product image requests failed or timed out for {impact_min} minutes. Cached images served normally. Conversion on product pages dipped during the window.",
    "action_items": [
        "Configure automatic origin failover to the replica bucket on latency or error thresholds.",
        "Enable stale-if-error (24h) on the CDN for /img/*.",
        "Add a bounded queue with fast 503 to image-resizer and lower origin timeout to 5s.",
    ],
    "issues": [
        {"repo": "tigerlily/image-resizer", "title": "Automatic origin failover to replica bucket",
         "labels": ["enhancement", "postmortem-action-item", "resilience"],
         "body": "From {incident_id}. Health-check both buckets, fail over when p99 > 2s or error rate > 5% over 1 minute, fail back after 10 minutes healthy."},
    ],
    "questions": [
        ("product images not loading", "semantic"),
        ("CDNOriginErrorRate", "keyword"),
        ("object store slow in one region", "semantic"),
        ("504 on /img/ paths", "hybrid"),
        ("stale-if-error", "keyword"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "clock_skew_jwt",
    "title": "Clock skew causing JWT validation failures",
    "primary": "auth-service",
    "services": ["auth-service", "api-gateway", "checkout-api"],
    "error_code": "JWT_NBF",
    "trigger": "infra",
    "duration": (20, 60),
    "phases": {
        "precursor": [
            ("api-gateway", "warning", "log", "chrony: system clock on {node} offset +{n}.{n2}s from upstream, source unreachable"),
            ("api-gateway", "warning", "log", "chrony: no NTP sources reachable from {node}, running free"),
        ],
        "onset": [
            ("api-gateway", "warning", "log", "JWT validation failed: token not yet valid (nbf is {n}s in the future) for request to {path} trace={trace}"),
            ("checkout-api", "warning", "log", "401 from api-gateway for freshly issued token, client retrying trace={trace}"),
            ("auth-service", "info", "log", "POST /oauth/token 200 {ms}ms issued token exp=+900s nbf=now"),
        ],
        "peak": [
            ("api-gateway", "error", "log", "JWT validation failed: token not yet valid (nbf is {n}s in the future) for request to {path} trace={trace}"),
            ("api-gateway", "error", "log", "GET {path} 401 invalid_token: nbf claim in future trace={trace}"),
            ("api-gateway", "critical", "alert", "[FIRING] Gateway401RateHigh rate={pct}% threshold=1%"),
            ("checkout-api", "error", "log", "POST /v1/checkout 401 rejected by gateway after successful login, user forced to re-authenticate trace={trace}"),
            ("auth-service", "warning", "log", "token refresh rate {n}/s, {pct}% above baseline (clients retrying after 401)"),
            ("api-gateway", "critical", "alert", "[FIRING] NodeClockSkew node={node} offset={n}.{n2}s threshold=1s"),
            ("auth-service", "warning", "alert", "[FIRING] AuthTokenRefreshStorm rate={n}/s"),
        ],
        "mitigation": [
            ("api-gateway", "info", "log", "incident {incident_id}: {oncall} found NTP egress blocked by new network policy on node pool gateway, allowing udp/123"),
            ("api-gateway", "info", "log", "chrony: selected source time.cloud.internal, stepping clock by -{n}.{n2}s on {node}"),
            ("api-gateway", "info", "log", "JWT validator clock skew tolerance raised 0s -> 30s (manual: {oncall})"),
        ],
        "recovery": [
            ("api-gateway", "info", "alert", "[RESOLVED] Gateway401RateHigh rate=0.2%"),
            ("api-gateway", "info", "alert", "[RESOLVED] NodeClockSkew node={node} offset=0.002s"),
            ("auth-service", "info", "alert", "[RESOLVED] AuthTokenRefreshStorm"),
            ("api-gateway", "info", "log", "GET {path} 200 {ms}ms trace={trace}"),
        ],
    },
    "runbook": {
        "Symptoms": "Freshly issued tokens are rejected as 'not yet valid' or 'expired' by some gateway replicas but not others. Users are logged out or asked to re-authenticate repeatedly. Token refresh traffic spikes. The auth service itself reports no errors.",
        "Detection": "Alerts: Gateway401RateHigh, NodeClockSkew, AuthTokenRefreshStorm. Dashboard: Platform > Nodes > clock offset.",
        "Diagnosis": "Compare 'date' across gateway nodes and the auth-service nodes. If offsets exceed a second, find out why NTP stopped syncing: chrony logs will show unreachable sources, which usually means a network policy or firewall change blocked udp/123. JWT nbf and exp are strict unless the validator has a skew tolerance.",
        "Mitigation": "Restore NTP reachability and let chrony step the clock (or restart chronyd with makestep). As a stop-gap raise the validator's clock skew tolerance to 30 seconds. Do not disable nbf or exp validation.",
        "Verification": "Clock offsets under 100ms on all nodes. 401 rate at baseline. Refresh storm subsides within a few minutes as clients settle.",
        "Escalation": "Page platform-infra. Page identity if the fix requires an auth-service change.",
    },
    "root_cause": "A new default-deny egress NetworkPolicy on the gateway node pool blocked UDP port 123. chrony lost all NTP sources and the nodes drifted. After about 30 hours, two of the eight gateway nodes were more than 4 seconds behind the auth-service nodes. Tokens issued with nbf=now were rejected by those gateway replicas as not yet valid, and the validator had zero skew tolerance.",
    "contributing": [
        "The network policy change did not include NTP in its allowlist.",
        "NodeClockSkew alert threshold was 5 seconds, so it fired late.",
        "JWT validation allowed zero clock skew.",
    ],
    "impact": "About {impact_pct}% of authenticated requests (those hitting the two skewed replicas) were rejected for {impact_min} minutes, forcing re-login. Token refresh traffic tripled.",
    "action_items": [
        "Add NTP (udp/123) to the baseline egress allowlist for every node pool.",
        "Lower NodeClockSkew threshold to 500ms.",
        "Set JWT validator skew tolerance to 30s permanently.",
    ],
    "issues": [
        {"repo": "tigerlily/api-gateway", "title": "JWT validator should tolerate 30s clock skew",
         "labels": ["bug", "sev3", "postmortem-action-item", "auth"],
         "body": "Zero tolerance turned a 4s node drift into user-facing 401s in {incident_id}. Set leeway=30s for nbf/exp/iat."},
        {"repo": "tigerlily/db-ops", "title": "Baseline egress NetworkPolicy missing NTP",
         "labels": ["bug", "postmortem-action-item", "kubernetes", "networking"],
         "body": "The default-deny egress policy for node pool gateway blocked udp/123 and nodes drifted for 30 hours before {incident_id}. Add NTP to the baseline allow set and add a conformance test."},
    ],
    "questions": [
        ("users being logged out randomly", "semantic"),
        ("token not yet valid", "keyword"),
        ("clock skew between nodes", "hybrid"),
        ("NTP blocked by network policy", "semantic"),
        ("401 errors only from some gateway replicas", "semantic"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "autoscaler_flapping",
    "title": "HPA flapping on api-gateway causing latency spikes",
    "primary": "api-gateway",
    "services": ["api-gateway"],
    "error_code": "HPA_FLAP",
    "trigger": "config",
    "duration": (60, 150),
    "phases": {
        "precursor": [
            ("api-gateway", "info", "log", "config reload complete, HPA target cpu 70% -> 45%, stabilization window 300s -> 0s"),
            ("api-gateway", "info", "log", "autoscaler scaled api-gateway from 8 to 14 replicas (cpu 71%)"),
        ],
        "onset": [
            ("api-gateway", "info", "log", "autoscaler scaled api-gateway from 14 to 6 replicas (cpu 22%)"),
            ("api-gateway", "warning", "log", "upstream checkout-api response time p99 {slow_ms}ms exceeds SLO 800ms (replica warm-up)"),
            ("api-gateway", "info", "log", "autoscaler scaled api-gateway from 6 to 16 replicas (cpu 88%)"),
        ],
        "peak": [
            ("api-gateway", "info", "k8s_event", "HorizontalPodAutoscaler api-gateway: SuccessfulRescale, New size: {n2}; reason: cpu resource utilization above target"),
            ("api-gateway", "info", "k8s_event", "HorizontalPodAutoscaler api-gateway: SuccessfulRescale, New size: {n2}; reason: All metrics below target"),
            ("api-gateway", "warning", "log", "route /v1/checkout 499 client closed request before upstream responded (new replica warming JIT/conn pools)"),
            ("api-gateway", "error", "log", "route /v1/search 504 upstream search-api timed out after 30s trace={trace} (replica {pod} age 40s)"),
            ("api-gateway", "critical", "alert", "[FIRING] HPAFlapping deployment=api-gateway rescales_15m={n2} threshold=4"),
            ("api-gateway", "warning", "alert", "[FIRING] GatewayLatencyP99 p99={slow_ms}ms threshold=800ms"),
            ("api-gateway", "warning", "log", "connection pool to checkout-api cold on {pod}, {n} connections warming"),
        ],
        "mitigation": [
            ("api-gateway", "info", "log", "incident {incident_id}: {oncall} restored HPA stabilization window 300s and target cpu 60%, min replicas 8 -> 10"),
            ("api-gateway", "info", "k8s_event", "HorizontalPodAutoscaler api-gateway: configuration updated, behavior.scaleDown.stabilizationWindowSeconds=300"),
        ],
        "recovery": [
            ("api-gateway", "info", "log", "HPA api-gateway: current replicas 12, desired 12, cpu utilization 58%"),
            ("api-gateway", "info", "alert", "[RESOLVED] HPAFlapping deployment=api-gateway rescales_15m=0"),
            ("api-gateway", "info", "alert", "[RESOLVED] GatewayLatencyP99 p99=190ms"),
        ],
    },
    "runbook": {
        "Symptoms": "Replica count oscillates every minute or two. Latency spikes coincide with scale events as new replicas serve traffic before their connection pools and caches are warm. Error rate stays low but p99 is terrible.",
        "Detection": "Alerts: HPAFlapping (more than 4 rescales in 15 minutes), GatewayLatencyP99. Dashboard: replica count overlaid on p99.",
        "Diagnosis": "kubectl describe hpa shows the rescale events and reasons. Look for a recent change to target utilization, stabilization window, or metrics. A target set too close to idle CPU, combined with a zero stabilization window, guarantees oscillation: scale up drops per-pod CPU below target, scale down raises it above.",
        "Mitigation": "Restore a scale-down stabilization window of at least 300 seconds and a sane target (60% for the gateway). Raise minReplicas so warm-up cost is amortized. If flapping is severe, temporarily pin replicas by removing the HPA and setting a fixed count.",
        "Verification": "Replica count stable for 30 minutes. p99 under SLO.",
        "Escalation": "Platform-infra owns the gateway HPA.",
    },
    "root_cause": "A cost-optimization change lowered the api-gateway HPA target from 70% to 45% and set the scale-down stabilization window to zero to 'react faster'. With the gateway's per-replica warm-up cost, each scale-up immediately dropped utilization below 45%, triggering scale-down, which pushed it above again. The deployment oscillated between 6 and 16 replicas for two hours.",
    "contributing": [
        "HPA changes were not reviewed by the service owners.",
        "No alert existed on rescale frequency until this incident.",
        "New gateway replicas take about 40 seconds to warm connection pools.",
    ],
    "impact": "Gateway p99 latency exceeded SLO for {impact_min} minutes with periodic bursts of 499 and 504. Error rate stayed under 1%.",
    "action_items": [
        "Require service-owner review for HPA changes via CODEOWNERS.",
        "Add HPAFlapping alert for all tier-1 deployments.",
        "Add a readiness gate that warms connection pools before a gateway replica receives traffic.",
    ],
    "issues": [
        {"repo": "tigerlily/api-gateway", "title": "Warm connection pools before readiness",
         "labels": ["enhancement", "postmortem-action-item", "performance"],
         "body": "New replicas caused p99 spikes during {incident_id}. Open N connections to each upstream and issue a health request before reporting ready."},
    ],
    "questions": [
        ("gateway replicas scaling up and down constantly", "semantic"),
        ("HPAFlapping", "keyword"),
        ("latency spikes every time we scale", "semantic"),
        ("stabilizationWindowSeconds", "keyword"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "poison_message",
    "title": "Poison message stalling the notifications consumer",
    "primary": "notifications",
    "services": ["notifications", "kafka"],
    "error_code": "DESERIALIZE_ERROR",
    "trigger": "external",
    "duration": (45, 120),
    "phases": {
        "precursor": [
            ("notifications", "info", "log", "consumed {n} messages from notifications.email partition {partition} offset={offset} lag={lag_small}"),
            ("order-service", "info", "log", "published order.confirmed event for order {id} to notifications.email (schema v4, producer build {sha})"),
        ],
        "onset": [
            ("notifications", "error", "log", "unhandled exception in email-dispatch: JSON parse error at offset {offset}: unexpected token in field 'recipient' (schema v4 field renamed?)"),
            ("notifications", "warning", "log", "consumer for partition {partition} restarting from committed offset {offset}, message will be retried"),
            ("notifications", "error", "log", "unhandled exception in email-dispatch: JSON parse error at offset {offset}: unexpected token in field 'recipient'"),
        ],
        "peak": [
            ("notifications", "error", "log", "unhandled exception in email-dispatch: JSON parse error at offset {offset}: unexpected token in field 'recipient'"),
            ("notifications", "warning", "log", "consumer for partition {partition} restarting from committed offset {offset}, retry {n2} of unlimited"),
            ("kafka", "warning", "log", "consumer lag on notifications.email partition {partition} is {lag} messages (threshold 1000), other partitions lag < 50"),
            ("kafka", "warning", "alert", "[FIRING] KafkaConsumerLagHigh group=notifications topic=notifications.email lag={lag}"),
            ("notifications", "warning", "alert", "[FIRING] ConsumerPartitionStalled group=notifications partition={partition} offset_unchanged_for={n}m"),
            ("notifications", "warning", "log", "email delivery delayed for {n} recipients whose keys hash to partition {partition}"),
        ],
        "mitigation": [
            ("notifications", "info", "log", "incident {incident_id}: {oncall} copied message at offset {offset} to notifications.email.dlq and advanced consumer offset"),
            ("notifications", "info", "log", "consumer for partition {partition} resumed from offset {offset_plus}, processing"),
            ("order-service", "info", "log", "rolled back producer schema change (recipient -> recipient_address) pending consumer support"),
        ],
        "recovery": [
            ("notifications", "info", "log", "consumed {n} messages from notifications.email partition {partition} offset={offset} lag={lag_small}"),
            ("kafka", "info", "alert", "[RESOLVED] KafkaConsumerLagHigh group=notifications lag=15"),
            ("notifications", "info", "alert", "[RESOLVED] ConsumerPartitionStalled group=notifications partition={partition}"),
        ],
    },
    "runbook": {
        "Symptoms": "One partition's lag grows while the others stay flat. The consumer logs the same exception at the same offset repeatedly. Downstream effects hit only a subset of users (those whose keys hash to the stuck partition).",
        "Detection": "Alerts: ConsumerPartitionStalled (offset unchanged for N minutes with lag), KafkaConsumerLagHigh. Dashboard: lag by partition.",
        "Diagnosis": "Read the message at the stuck offset with kcat or the Kafka UI. Usually it fails schema validation or deserialization, often because a producer shipped a schema change first. Check which producer build wrote it.",
        "Mitigation": "Copy the message to the DLQ topic and advance the consumer group's offset past it (kafka-consumer-groups --reset-offsets --to-offset for that partition, with the group stopped). Then stop the producer from emitting more, by rollback or hotfix. Long term the consumer must route undeserializable messages to the DLQ automatically.",
        "Verification": "Offset advancing on the partition. Lag draining. No new parse errors.",
        "Escalation": "Owning team. Coordinate with the producer's team for the schema fix.",
    },
    "root_cause": "order-service renamed the 'recipient' field to 'recipient_address' in the order.confirmed event and began producing the new shape before notifications supported it. The notifications consumer treated the deserialization failure as a transient error and retried the same offset forever, stalling one partition. Messages behind it were delayed for two hours.",
    "contributing": [
        "No schema registry compatibility check gated producer deploys.",
        "The consumer's error handling did not distinguish permanent from transient failures.",
        "Per-partition stall detection did not exist until this incident.",
    ],
    "impact": "Roughly {impact_pct}% of order confirmation emails (one partition of six) were delayed by up to {impact_min} minutes. No messages were lost.",
    "action_items": [
        "Route deserialization failures to the DLQ after 3 attempts instead of retrying indefinitely.",
        "Add schema registry compatibility checks (BACKWARD) to producer CI.",
        "Keep the ConsumerPartitionStalled alert for all consumer groups.",
    ],
    "issues": [
        {"repo": "tigerlily/notifications", "title": "Consumer retries undeserializable messages forever",
         "labels": ["bug", "sev3", "postmortem-action-item", "kafka"],
         "body": "In {incident_id} a single malformed message blocked a partition for two hours. Classify deserialization errors as permanent, DLQ after 3 attempts, and emit a metric."},
        {"repo": "tigerlily/order-service", "title": "Event schema change shipped without consumer compatibility",
         "labels": ["bug", "postmortem-action-item", "kafka", "schema"],
         "body": "recipient -> recipient_address broke notifications in {incident_id}. Register schemas and enforce BACKWARD compatibility in CI; field renames need a dual-write period."},
    ],
    "questions": [
        ("one kafka partition stuck while others are fine", "semantic"),
        ("JSON parse error at offset", "keyword"),
        ("poison message", "hybrid"),
        ("some customers not getting confirmation emails", "semantic"),
        ("ConsumerPartitionStalled", "keyword"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "replica_lag_stale_reads",
    "title": "Read replica lag causing stale order status",
    "primary": "postgres",
    "services": ["postgres", "order-service", "user-profile"],
    "error_code": "REPLICA_LAG",
    "trigger": "capacity",
    "duration": (40, 100),
    "phases": {
        "precursor": [
            ("postgres", "info", "log", "replication slot replica_us_east_1 confirmed flush lsn {lsn}"),
            ("scheduler", "info", "log", "scheduled job price-history-rollup started run_id={id} (backfill mode, 90 days)"),
            ("postgres", "warning", "log", "replica tigerlily-replica-1: replay lag {n}s, apply blocked by conflicting query (pid {id})"),
        ],
        "onset": [
            ("postgres", "warning", "log", "replica tigerlily-replica-1: replay lag {n}s, write_lag 0.{ms}s flush_lag 0.{ms}s"),
            ("postgres", "warning", "alert", "[FIRING] PostgresReplicaLagHigh replica=tigerlily-replica-1 lag={n}s threshold=30s"),
            ("order-service", "warning", "log", "order {id} status read from replica returned PENDING, primary says CONFIRMED (lag suspected)"),
        ],
        "peak": [
            ("postgres", "warning", "log", "replica tigerlily-replica-1: replay lag {n_big}s, WAL receive ok, recovery conflict canceled {n2} queries"),
            ("postgres", "error", "log", "ERROR: canceling statement due to conflict with recovery  DETAIL: User query might have needed to see row versions that must be removed."),
            ("order-service", "error", "log", "GET order {id} status 200 but stale: customer sees 'processing' {n} minutes after shipment scan"),
            ("user-profile", "warning", "log", "GET /v1/users/{id} 200 {ms}ms served from replica with {n}s lag, recently updated address may be stale"),
            ("postgres", "critical", "alert", "[FIRING] PostgresReplicaLagCritical replica=tigerlily-replica-1 lag={n_big}s threshold=300s"),
            ("order-service", "warning", "alert", "[FIRING] OrderStatusStaleReads rate={pct}% (replica vs primary mismatch sample)"),
            ("scheduler", "warning", "log", "job price-history-rollup running {n} minutes, {n2}M rows written to price_history"),
        ],
        "mitigation": [
            ("postgres", "info", "log", "incident {incident_id}: {oncall} paused price-history-rollup backfill (WAL generation 400MB/min) and routed order-status reads to primary"),
            ("order-service", "info", "log", "read routing: order status queries pinned to primary (feature flag reads-prefer-primary=on)"),
            ("postgres", "info", "log", "replica tigerlily-replica-1: replay lag {n}s and falling"),
        ],
        "recovery": [
            ("postgres", "info", "log", "replica tigerlily-replica-1: replay lag 0.{ms}s"),
            ("postgres", "info", "alert", "[RESOLVED] PostgresReplicaLagCritical replica=tigerlily-replica-1"),
            ("postgres", "info", "alert", "[RESOLVED] PostgresReplicaLagHigh replica=tigerlily-replica-1 lag=1s"),
            ("order-service", "info", "alert", "[RESOLVED] OrderStatusStaleReads rate=0%"),
        ],
    },
    "runbook": {
        "Symptoms": "Customers see out-of-date order status or profile data. Writes succeed but reads do not reflect them for seconds to minutes. Replica replay lag is high. Some replica queries are cancelled with 'conflict with recovery'.",
        "Detection": "Alerts: PostgresReplicaLagHigh (30s), PostgresReplicaLagCritical (300s), OrderStatusStaleReads. Query on replica: SELECT now() - pg_last_xact_replay_timestamp().",
        "Diagnosis": "Determine whether the replica is receiving WAL but not applying it (replay lag with low flush lag: a long query on the replica is blocking apply, or apply is CPU/IO bound) or not receiving it (network, primary WAL sender). Check what is generating WAL on the primary: a bulk backfill or a large VACUUM is typical.",
        "Mitigation": "Pause the WAL-heavy job on the primary. Cancel long queries on the replica if hot_standby_feedback is off and they block apply. Route read-your-own-writes paths (order status, profile after edit) to the primary until lag recovers. Do not promote the replica.",
        "Verification": "Replay lag under 1 second. Stale-read sample rate at zero. Backfill resumed at a throttled rate.",
        "Escalation": "Page data-infra. Page fulfillment if order status is wrong for more than 15 minutes.",
    },
    "root_cause": "A 90-day price-history backfill run by scheduler generated WAL at roughly 400MB per minute. The single read replica could not apply WAL at that rate while also serving reporting queries, and lag climbed past ten minutes. order-service and user-profile read from the replica by default, so customers saw stale order status and profile data.",
    "contributing": [
        "Backfills ran at full speed with no WAL-rate throttle.",
        "The replica served both application reads and analytics queries.",
        "Read-your-own-writes paths were not pinned to the primary.",
    ],
    "impact": "Order status and profile reads were stale by up to {impact_min} minutes for {impact_pct}% of requests. Support received {impact_n} tickets about orders 'stuck in processing'.",
    "action_items": [
        "Throttle backfill jobs to a WAL budget (50MB/min) with automatic pause on replica lag.",
        "Pin read-your-own-writes queries to the primary via the session-after-write pattern.",
        "Add a second replica dedicated to analytics.",
    ],
    "issues": [
        {"repo": "tigerlily/scheduler", "title": "Backfill jobs need a WAL-rate throttle tied to replica lag",
         "labels": ["postmortem-action-item", "database", "capacity"],
         "body": "price-history-rollup generated 400MB/min of WAL in {incident_id}. Add a lag check between batches: pause when replica lag > 10s, resume under 2s."},
        {"repo": "tigerlily/order-service", "title": "Route order status reads to primary for 60s after a write",
         "labels": ["enhancement", "postmortem-action-item", "consistency"],
         "body": "Customers saw stale status during {incident_id}. Implement read-after-write pinning keyed on order id with a 60s TTL in Redis."},
    ],
    "questions": [
        ("order status shows processing after it shipped", "semantic"),
        ("replica lag", "keyword"),
        ("canceling statement due to conflict with recovery", "keyword"),
        ("stale reads after a backfill job", "hybrid"),
        ("customers seeing old data", "semantic"),
    ],
},
# ---------------------------------------------------------------------------
{
    "key": "feature_flag_misconfig",
    "title": "Feature flag rollout to 100% enabling broken checkout path",
    "primary": "checkout-api",
    "services": ["checkout-api", "payments"],
    "error_code": "FLAG_ROLLOUT",
    "trigger": "config",
    "duration": (10, 30),
    "phases": {
        "precursor": [
            ("checkout-api", "info", "log", "feature flag snapshot refreshed, 42 flags loaded from config service (checkout-express-v2: 5% -> 100%)"),
            ("checkout-api", "info", "log", "checkout-express-v2 path selected for {pct}% of sessions"),
        ],
        "onset": [
            ("checkout-api", "error", "log", "POST /v1/checkout/{id}/confirm 500 express-v2: tax quote missing for region {region}, provider not configured trace={trace}"),
            ("checkout-api", "error", "log", "POST /v1/checkout/{id}/shipping 500 express-v2: shipping options empty for non-US address trace={trace}"),
            ("checkout-api", "warning", "log", "error rate for path=express-v2 is {pct}%, legacy path 0.3%"),
        ],
        "peak": [
            ("checkout-api", "error", "log", "POST /v1/checkout/{id}/confirm 500 express-v2: tax quote missing for region {region}, provider not configured trace={trace}"),
            ("checkout-api", "critical", "alert", "[FIRING] CheckoutErrorRateHigh error_rate={pct}% threshold=2% window=5m"),
            ("checkout-api", "critical", "alert", "[FIRING] CheckoutConversionDrop region=eu-central-1 conversion={pct}% baseline=68%"),
            ("payments", "info", "log", "served {n} requests in last 60s, authorize volume down {pct}% vs same hour last week"),
            ("checkout-api", "error", "log", "POST /v1/checkout/{id}/confirm 500 express-v2: NullPointer in AddressNormalizer for postal code format {id} trace={trace}"),
        ],
        "mitigation": [
            ("checkout-api", "info", "log", "incident {incident_id}: {oncall} set checkout-express-v2 back to 5% US-only via config service kill switch"),
            ("checkout-api", "info", "log", "feature flag snapshot refreshed, 42 flags loaded from config service (checkout-express-v2: 100% -> 5%, rule: country=US)"),
        ],
        "recovery": [
            ("checkout-api", "info", "log", "POST /v1/checkout/{id}/confirm 201 {ms}ms trace={trace}"),
            ("checkout-api", "info", "alert", "[RESOLVED] CheckoutErrorRateHigh error_rate=0.3%"),
            ("checkout-api", "info", "alert", "[RESOLVED] CheckoutConversionDrop region=eu-central-1 conversion=67%"),
        ],
    },
    "runbook": {
        "Symptoms": "Error rate or conversion changes sharply with no deploy in the timeline. Errors concentrate in one code path, region, or customer segment. Flag change events appear in the config service audit log.",
        "Detection": "Alerts: CheckoutErrorRateHigh, CheckoutConversionDrop. The flag change shows on the flags panel of the checkout dashboard.",
        "Diagnosis": "Check the config service audit log for changes in the last hour. Compare error rate split by flag variant. If the new variant is failing, that is the cause; no further diagnosis needed during the incident.",
        "Mitigation": "Use the flag kill switch to return to the previous rollout percentage and targeting rules. Flag changes take effect within 30 seconds; no deploy needed. Do not fix forward in code during the incident.",
        "Verification": "Error rate and conversion return to baseline within two minutes. Variant split confirms traffic is off the failing path.",
        "Escalation": "Owning team. SEV1 if checkout error rate exceeds 10%.",
    },
    "root_cause": "The checkout-express-v2 flag was meant to move from 5% to 25% for US customers only. The operator changed the percentage to 100% and removed the country rule in the same edit. The express path had no tax provider configured for non-US regions and its address normalizer failed on several postal code formats, so most non-US checkouts errored.",
    "contributing": [
        "The flag UI allowed percentage and targeting rules to change in one step with no confirmation for tier-1 flags.",
        "No guardrail metric (error rate per variant) was attached to the flag.",
        "Express v2 had only been tested with US addresses.",
    ],
    "impact": "Roughly {impact_pct}% of non-US checkouts failed for {impact_min} minutes, about {impact_orders} orders. US checkouts were unaffected.",
    "action_items": [
        "Require two-person approval for tier-1 flag changes over 25% or that remove targeting rules.",
        "Attach an automatic guardrail: revert the flag if variant error rate exceeds 2x control for 3 minutes.",
        "Add non-US address fixtures to express v2 tests.",
    ],
    "issues": [
        {"repo": "tigerlily/checkout-api", "title": "Express v2 checkout fails for non-US addresses",
         "labels": ["bug", "sev2", "postmortem-action-item", "checkout"],
         "body": "Exposed by {incident_id}. Tax provider not configured for EU/APAC and AddressNormalizer assumes US ZIP format. Add fixtures for DE, FR, JP, SG, AU postal codes."},
    ],
    "questions": [
        ("checkout broke for european customers with no deploy", "semantic"),
        ("checkout-express-v2", "keyword"),
        ("feature flag rollout caused errors", "hybrid"),
        ("conversion dropped in eu-central-1", "semantic"),
    ],
},
]
